### ISSUE TITLE
callBack for responseCode not set

### ISSUE THREAD

**Issue by marioanton** [census-instrumentation/opencensus-python#1013]
Running an azure queue trigger function.
Natively application insights logging for queue triggers return 0 as response code.
According to their docs, and other issues visiter this can be achieved with opencensus.

**Steps to reproduce.**
        def callback_function(envelope):
            envelope.data.baseData.responseCode = 400
            return True

**What is the expected behavior?**
i would expect the responseCode to be updated in applicationInsights.
**What is the actual behavior?**
Response code isn't updated.

**Additional context.**
NA

**Comment by lzchen** [comment]
@marioanton 
Are you adding the telemetryprocessor to the AzureExporter?

`exporter.add_telemetryprocessor(callback_function)`

**Comment by marioanton** [comment]
Hi @lzchen yes. I am using that bit too.

Here is the bit of the code i am using while doing testing:

`      logger = logging.getLogger('opencensus')
        def callback_function(envelope):
            envelope.data.baseData.responseCode = 400
            return True

        telemetry_handler = AzureLogHandler(connection_string='InstrumentationKey=xxxxx-xxxx-xxxx')
        telemetry_handler.setLevel(logging.INFO)
        telemetry_handler.add_telemetry_processor(callback_function)
`

**Comment by lzchen** [comment]
Are you adding the `telemetry_handler` to the logger?
`logger.addHandler(telemetry_handler)`

As well, how are you using the logger? `logger.INFO`? Are you seeing ANY telemetry at all?

**Comment by lzchen** [comment]
@marioanton 
You are using the `AzureLogHandler` which is responsible for sending log telemetry and populates the `trace` table in AppInsights. This type of telemetry does not have the `responseCode` field. If you take a look in AppInsights `trace` table, even without the telemetry_processor, there is not column for `responseCode`.

If you want to keep track of the `responseCode` using your logs, you can add it as via `properties`. Then you will be able to see it under `custom_dimension` in AppInsights.

```
logger = logging.getLogger('opencensus')
def callback_function(envelope):
    envelope.data.baseData.properties['responseCode'] = str(400)
    return True

telemetry_handler = AzureLogHandler()
telemetry_handler.add_telemetry_processor(callback_function)
logger.addHandler(telemetry_handler)

logger.warning("test")
```

**Comment by marioanton** [comment]
Hi @lzchen  and thanks for coming back to me that quick again.
That works pretty well but is adding a Custom Property and not modifying the Request property which is what i am aiming to.
Guess i'm getting this wrong.  Is there a way to modify the request property mentioned?

i am following the bit https://pypi.org/project/opencensus-ext-azure/ for Logging but i am guessing now i should pick up Integrations bit to trace request.

Feel free to close the ticket anyway if you think there is no way to achieve that and.

thanks in advance.

**Comment by lzchen** [comment]
@marioanton 
Please refer to this [docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python) for how to setup your application to collect request telemetry (specifically the [tracing](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python) portion).

> Feel free to close the ticket anyway if you think there is no way to achieve that and.

This is definitely doable, I believe you just need to setup your application properly. I will close the ticket and feel free to comment on the thread again if you have difficulties achieving what you need.

**Comment by marioanton** [comment]
Hi @lzchen. Sorry for bothering again. Perhaps this is one to be created in  a separate thread.
I got to the point where i am seeing the dependencies being logged properly but all the requests are dupe in application insights.

Have seem this for some other exported from opencensus for nodejs. MIght be related..

Just got a code example from Ms  so that you can replay this:


`import requests
from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.trace import config_integration
from opencensus.trace.samplers import ProbabilitySampler
from opencensus.trace.tracer import Tracer

config_integration.trace_integrations(['requests'])  # <-- this line enables the requests integration

tracer = Tracer(exporter=AzureExporter(connection_string="InstrumentationKey=xxxxxxx"), sampler=ProbabilitySampler(1.0))

with tracer.span(name='parent'):
    response = requests.get(url='http://127.0.0.1:8082') # <-- this request will be track`

**Comment by lzchen** [comment]
Hey thanks for the bug report. Yes this is a known bug in the requests integration sending out duplicate telemetry. See [here](https://github.com/census-instrumentation/opencensus-python/issues/956#issuecomment-702288362). We should have a fix for this soon.

**Comment by marioanton** [comment]
cheers :)
