### ISSUE TITLE
How are metrics tags exposed in Azure Application Insights?

### ISSUE THREAD

**Issue by freemansoft** [census-instrumentation/opencensus-python#1015]
How are custom tags sent to Azure?  Are they sent as _MetricData_ properties? If so, how are they exposed in the Azure dashboard?

Looking at the code in the various __init__.py files. 

* It looks like __envelope__ tags come from `utils.azure_monitor_context`.  
* Envelop tags are exposed in azure for _filtering_ and _splitting_  which lets you break out individual hosts or locations

**Metrics exporter**  __init__.py
```
   def _create_envelope(self, data_point, timestamp, properties):
        envelope = Envelope(
            iKey=self.options.instrumentation_key,
            tags=dict(utils.azure_monitor_context),
            time=timestamp.isoformat(),
        )
        envelope.name = "Microsoft.ApplicationInsights.Metric"
        data = MetricData(
            metrics=[data_point],
            properties=properties
        )
        envelope.data = Data(baseData=data, baseType="MetricData")
        return envelope
```

The context has a hardcoded set of attributes that align with the Azure AppInsights attributes
**common** `utils.py`
```
azure_monitor_context = {
    'ai.cloud.role': os.path.basename(sys.argv[0]) or 'Python Application',
    'ai.cloud.roleInstance': platform.node(),
    'ai.device.id': platform.node(),
    'ai.device.locale': locale.getdefaultlocale()[0],
    'ai.device.osVersion': platform.version(),
    'ai.device.type': 'Other',
    'ai.internal.sdkVersion': 'py{}:oc{}:ext{}'.format(
        platform.python_version(),
        opencensus_version,
        ext_version,
    ),
}
```

**Comment by lzchen** [comment]
@freemansoft 
Custom tags are exposed as customDimensions in Application Insights log view.

![image](https://user-images.githubusercontent.com/11580155/109848733-708e8080-7c05-11eb-8fb4-f12983d98c94.png)

You can filter by customDimensions in the metrics explorer view.

![image](https://user-images.githubusercontent.com/11580155/109849041-c6fbbf00-7c05-11eb-9e39-9ba7afc0e7f1.png)

**Comment by freemansoft** [comment]
Got it.  

Tags are exposed as customDimensions when they are added to the view columns/dimensions list as part of the view definition.

I didn't realize I needed to add the tag keys to the view.

**Comment by freemansoft** [comment]
Here are a couple more detailed guides on how to do this.
- http://joe.blog.freemansoft.com/2021/03/displaying-python-metrics-in-azure.html
- http://joe.blog.freemansoft.com/2021/03/querying-python-metrics-custom-tags-as.html
- http://joe.blog.freemansoft.com/2021/03/querying-python-logs-azure-application.html
