### ISSUE TITLE
Unable to specify AppVersion for Python app

### ISSUE THREAD

**Issue by scschneider** [census-instrumentation/opencensus-python#1017]
**Describe your environment.** 
Name: opencensus-ext-azure
Version: 1.0.7
Summary: OpenCensus Azure Monitor Exporter
Home-page: https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-azure
Author: OpenCensus Authors
Author-email: census-developers@googlegroups.com
License: Apache-2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: requests, opencensus, psutil

**Steps to reproduce.**
```python
import logging
import time
from opencensus.ext.azure.log_exporter import AzureLogHandler, AzureEventHandler

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

def envelope_callback(envelope):
    envelope.tags['ai.cloud.role'] = "PythonConsoleApp"
    envelope.tags['ai.component.version'] = "0.0.0.1"
    envelope.data.baseData.appVersion = "0.0.0.1"
    envelope.data.baseData.version = "0.0.0.1"
    envelope.data.baseData.ver = "0.0.0.1"
    print(envelope)

    return True

azure_log_handler = AzureLogHandler(
    connection_string='InstrumentationKey=*****')

azure_log_handler.add_telemetry_processor(envelope_callback)
logger.addHandler(azure_log_handler)

while True:
    logger.info("Python app")
    time.sleep(3)
```

**What is the expected behavior?**
I expect to see the AppVersion populate in the various Azure Monitor workspace tables, i.e., AppTraces
![image](https://user-images.githubusercontent.com/25066231/110226230-47d6e700-7ea2-11eb-99fc-90830a1cc75a.png)

**What is the actual behavior?**
Empty AppVersion regardless of the attempts to try and pass it down

**Comment by lzchen** [comment]
@scschneider 
Just to clarify, are you using [Log analytics workspace](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/quick-create-workspace) to query for your telemetry?

**Comment by scschneider** [comment]
@Izchen

> @scschneider
> Just to clarify, are you using [Log analytics workspace](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/quick-create-workspace) to query for your telemetry?

Yes, using the Log Analytics workspace. I just queried the Application Insights instance and that version is also empty:
![image](https://user-images.githubusercontent.com/25066231/110352513-de162480-7fea-11eb-9dd2-0bb78ea5eff8.png)

**Comment by lzchen** [comment]
`AppVersion` is an optional field in the workspaces and by default, the column does not show up, so Opencensus does not support populating it. I do not believe the other SDKs populate it as well. Are you able to put the "AppVersion" in the custom dimensions field instead?

**Comment by scschneider** [comment]
Using the C# Application Insights SDK, I am able to specify the version just fine using `telemetry.Context.Component.Version = "0.0.0.1";`. OpenCensus allows overriding/specifying the AppRoleName by setting an appropriate tag `envelope.tags['ai.cloud.role'] = "PythonConsoleApp"`. It would be good to follow this pattern for the version as well for AppVersion and placing it in the customDimensions section make the usability inconsistent. 

For context, we are looking to build observability across many different languages (C#, C++, Python and Java) in a consistent manner and give us the ability to query logs/metrics/events in a similar manner regardless of the language. Having things specialized for each language makes the end result feel clunky and adds additional overhead.

**Comment by lzchen** [comment]
@scschneider 
Apologies, I mistook the field name when going through the code.
Yes, we actually do support populating "AppVersion", see below:

def envelope_callback(envelope):
    envelope.tags['ai.application.ver'] = "0.0.0.1"

**Comment by scschneider** [comment]
This is great!! Are all of the "overridable" fields documented somewhere?

**Comment by lzchen** [comment]
@scschneider 
They are not, we probably should document them.
