### ISSUE TITLE
Missing requests data in app insights

### ISSUE THREAD

**Issue by jamescw** [census-instrumentation/opencensus-python#1018]
Hi all,

Apologies if this is not the right place but I tried a few things and really cannot work out why I am getting this behaviour.
I am using the requests integration in my Python Azure Function App, in the following example:

````python
from opencensus.trace import config_integration
from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.trace.samplers import ProbabilitySampler
from opencensus.trace.tracer import Tracer

config_integration.trace_integrations(["requests"])
app_insights_exporter = AzureExporter()
tracer = Tracer(exporter=app_insights_exporter, sampler=ProbabilitySampler(rate=1.0))

def callback_function(envelope):
    envelope.tags["ai.cloud.role"] = APP_NAME
    return True

app_insights_exporter.add_telemetry_processor(callback_function)

with tracer.span(name="requests"):
      try:
          response = session.post(
              "url", json=data
          )
````

![image](https://user-images.githubusercontent.com/440684/112214709-cca25e80-8c1f-11eb-8e48-b4306dde2ae2.png)

As you can see the trace is logged in AI, but does not have any of the properties it should have (dest URL for example is missing among many others). Furthermore, when debugging the requests integration I can see that the underlying tracer is a Noop tracer which probably explains why none of the attributes I should be seeing are present.

![image](https://user-images.githubusercontent.com/440684/112215820-18a1d300-8c21-11eb-94a2-287e1b123b7b.png)

What am I doing wrong here? I have looked at several examples both here and elsewhere for this integration but cannot see what the issue could be.

Many thanks in advance for any pointers!

**Comment by lzchen** [comment]
If for some reason you are using a NoopTracer, you wouldn't get ANY telemetry.
Just curious, how many pieces of telemetry are you getting just by running that sample code? You should get two `dependency` type telemetry, one `INPROC` representing the `tracer.span` and another for the actual `session.post`.

**Comment by jamescw** [comment]
Yes indeed, not meaning to use NoopTracer but that is what is getting passed!
I am using a `requests.Session()` object correct, I see only the INPROC trace in AI as a result, now I'm thinking this is related to #990 as requests sessions use `.send` transparently to actually send a prepared request.

![image](https://user-images.githubusercontent.com/440684/112226644-b223b180-8c2e-11eb-8ab5-fc0f498526ce.png)

**Comment by jamescw** [comment]
Thanks @izchen for taking a look at this. 

Generally I am issuing session post requests here: https://github.com/psf/requests/blob/2c2138e811487b13020eb331482fb991fd399d4e/requests/sessions.py#L579

This subsequently calls the sessions request method here:
https://github.com/psf/requests/blob/2c2138e811487b13020eb331482fb991fd399d4e/requests/sessions.py#L528

I have noticed that this actually does prepare a request `prep = self.prepare_request(req)` which is then sent using send:
https://github.com/psf/requests/blob/2c2138e811487b13020eb331482fb991fd399d4e/requests/sessions.py#L626

I'm not sure if the above is having any impact, but am only getting the INPROC dependency and not the `session.post` dependency which you mentioned above I should see.

I have set a breakpoint on line 88/89 on the `def wrap_session_request(wrapped, instance, args, kwargs)` wrapper which is invoked as expected but has a NoopTracer in its context when `execution_context.get_opencensus_tracer()` is called:
https://github.com/census-instrumentation/opencensus-python/blob/a82fa83b7a81f97bdbc9ecbec8750702a10a3c09/contrib/opencensus-ext-requests/opencensus/ext/requests/trace.py#L88

Which results in no telemetry as you pointed out. Hope this helps to see what could be going wrong here.

**Comment by lzchen** [comment]
@jamescw 
Yes, the requests integration [patches](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-requests/opencensus/ext/requests/trace.py#L64) `Session.request` which is the hotpath for your use case `session.post`. Your use case is not a prepared request. [Prepared requests](https://requests.readthedocs.io/en/master/user/advanced/#prepared-requests) directly call `Session.send` and the integration doesn't support calls directly made with `send`.

What version of `opencensus-ext-requests` are you using? Are you running the Python app as a standalone application?
Let's also try removing the `AzureExporter` from the `Tracer` because this doesn't seem like an exporter issue. Removing the exporter from the `Tracer` will default to printing the spans to the console so it will be easier for debugging.

**Comment by jamescw** [comment]
Hi, @lzchen just coming back to you on this one after a long while. I did manage to get this to work in the context of a python function app, by initializing the integrations and exporters in the body of the function itself. What is probably happening is that the function app runtime spawns a worker for each function innovation so a tracer defined outside of this function actually had a different scope to the executing code that was being run in another context, below example works for my use case of a function app which listens for messages on a service bus queue:

```python

from opencensus.trace import config_integration
from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.trace.samplers import ProbabilitySampler
from opencensus.trace.tracer import Tracer

def callback_function(envelope):
    envelope.tags["ai.cloud.role"] = os.environ.get("APP_NAME")
    return True

def main(msgIn: func.ServiceBusMessage, msgOut: func.Out[str]):
    """Main method of the Message Consumer which orchistrates the
    reciving of the message from the queue and passes this to the request
    processor. The result is then captured and wrapped into a message that is
    sent back to a queue or topic to notify other systems

    Args:
        msgIn (func.ServiceBusMessage): Message recevied from the service bus for processing
        msgOut (func.Out[str]): The result of the processing operation wrapped into a message

    Raises:
        exp: Any exception raised during the processing of the message that could not be handled
    """
    # configure tracing for app insights integrations
    config_integration.trace_integrations(["requests"])
    app_insights_exporter = AzureExporter()
    tracer = Tracer(
        exporter=app_insights_exporter, sampler=ProbabilitySampler(rate=1.0)
    )
    app_insights_exporter.add_telemetry_processor(callback_function)

    ...

```

With this setup, I get a complete App Map and custom dimensions within exceptions that I raise from this code. Hopefully useful for anyone else not seeing traces from python function apps.

<img width="475" alt="Screenshot 2021-08-04 at 20 45 41" src="https://user-images.githubusercontent.com/440684/128237661-151b06ce-3bc0-4c5f-8304-36674c6570bb.png">

**Comment by lzchen** [comment]
@jamescw 

Hey thanks for taking a look into this. Yes your current solution would work in defining the the OpenCensus components within the function itself. However you will not get a correct trace if you were to call the function from another tracked service (the trace will be broken since the context in the function app will not be the same as the context of the call that called the function app). We have a recommended solution for functions customers [here](https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-azure#integrate-with-azure-functions). Feel free to comment if you need assistance in setting this up.

**Comment by jamescw** [comment]
@lzchen This is great happy to see a library made for python function apps. Do you have an example that also demonstrates how to properly capture exceptions raised in fucntions to AI with custom dimensions?

**Comment by lzchen** [comment]
@jamescw 

The library is made specifically for tracing components (which is separate from exceptions which is specific to logging). To log exceptions, you log things normally with `logging.exception` with custom dimensions as shown [here](https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-azure#custom-properties)

**Comment by jamescw** [comment]
Yes I am using that, but in the Python Function App environment, I am not getting consistent behavior. After you pointed out the new extension for python functions my setup now looks like this:

```python
def callback_function(envelope):
    envelope.tags["ai.cloud.role"] = os.environ.get("APP_NAME")
    return True

# configure tracing for app insights integrations
config_integration.trace_integrations(["requests"])
OpenCensusExtension.configure()
logger.addHandler(AzureLogHandler())
````
So this is working well but I need to figure out a way to add the telemetry handler as I did before because otherwise AI will map two entities, like this:

![image](https://user-images.githubusercontent.com/440684/128422908-4bd29727-27df-420e-b35f-1de6297ad7b5.png)

Setting the `ai.cloud.role` corrected to this issue as shown above `app_insights_exporter.add_telemetry_processor(callback_function)`

Now for exceptions, I am logging them like this:

```python
def transform(data: dict, template: str):
    try:
        template = env.get_template(f"{template}.jinja")
        rendered = template.render(**data)
        logger.debug(rendered)
        converted = json.loads(rendered)
        return converted
    except JSONDecodeError:
        logger.exception(
            "Exception raised during JSON conversion of rendered data",
            extra={
                "custom_dimensions": {
                    "template": template,
                    "data": json.dumps(data),
                    "rendered": rendered or None,
                }
            },
        )
        raise
```
But what I get in AI is this:

![image](https://user-images.githubusercontent.com/440684/128424333-f3113419-bda5-445f-a831-c6bb18a7bfd3.png)

The function runtime is catching it and wrapping it so then the custom_dimentions never make it to AI:

![image](https://user-images.githubusercontent.com/440684/128424535-23376e4d-e09c-4064-896b-ac1aca93d1c0.png)

I'm still puzzled by that one is there anything that should be done specifically for function apps?

**Comment by lzchen** [comment]
> Setting the ai.cloud.role corrected to this issue as shown above app_insights_exporter.add_telemetry_processor(callback_function)

You can access the exporter being used in the extension via `OpenCensusExtension._exporter`. See [here](https://github.com/census-ecosystem/opencensus-python-extensions-azure/blob/main/extensions/functions/src/opencensus/extension/azure/functions.py#L46). We will probably add an api to do this, but for now you can access it directly.

> The function runtime is catching it and wrapping it so then the custom_dimentions never make it to AI:

This is a current gap in the feature set for the functions runtime logger and OpenCensus logger. The Opencensus logger allows for custom dimension logging, but the functions runtime does not. We are currently addressing this issue to get parity between the two (most likely, we will be suppressing logs from functions logger and using OpenCensus instead). For now, you can try clearing the handlers in the root logger first, and then adding the `AzureLogHandler()` as usual.

```
logger = logging.getLogger()
while logger.hasHandlers():
  logger.removeHandler(logger.handlers[0])
logger.addHandler(AzureLogHandler())
```

**Comment by jamescw** [comment]
Closing this one out, all is good so far, as @lzchen says, some more work to be done at some point to make this play nice with Azure Functions but there are some workarounds (see above). Thanks for all the timely help on this one.
