### ISSUE TITLE
Opencensus not working with Flask 2

### ISSUE THREAD

**Issue by bogdancondurache** [census-instrumentation/opencensus-python#1022]
**Describe your environment.** 
I'm using Python 3.8 and because of some performance changes in Flask 2, I will need to use it, even if it's an RC version. Namely `Flask==2.0.0rc1`. Now, the problem is that opencensus-ext-flask has a dependency on Flask with version `< 2`. This is not a bug per se, nor a feature, but it would be nice to have opencensus-ext-flask see Flask 2 as a valid dependency, without us having to clone it and change that dependency

**Steps to reproduce.**
Install `Flask==2.0.0rc1` and `opencensus-ext-flask==0.7.4`

**What is the expected behavior?**
Having them installed and working.

**What is the actual behavior?**
```
The conflict is caused by:
     opencensus-ext-flask 0.7.4 depends on flask<2.0.0 and >=0.12.3
```

**Comment by alexkyllo** [comment]
I also have a Flask application that is stuck on Flask <2.0.0 due to this dependency. Would the maintainer(s) of this package review a PR to add Flask 2 support if I opened one?

**Comment by mortendaehli** [comment]
I have added a PR for this one, but it may take some time before anyone is looking at it. Any idea how we can speed this up?

**Comment by bogdancondurache** [comment]
maybe @lzchen or @aabmass could help with this one
