### ISSUE TITLE
Using AzureLogHandler and AzureEventHandler together

### ISSUE THREAD

**Issue by dalavayi** [census-instrumentation/opencensus-python#1024]
hi, 
i am trying to log traces(information, warnings, exceptions) using Azureloghandler, i want to log few custom events along with this, if i attach an event handler to my logger, all of my traces are also getting logged as custom events, is there any work around that is supported to log few traces and few custom events into app insights independently at the same time.

Thank you

**Comment by lzchen** [comment]
@dalavayi 
Can you use a separate logger to attach to?

**Comment by Liubaituo** [comment]
@dalavayi  Do you solve it, can you  share  idea and  code, I have some question now.

**Comment by lzchen** [comment]
@Liubaituo 
Please open up a new issues for issues that are not relevant to the original topic.

**Comment by lzchen** [comment]
@dalavayi 
Are you still having problems with this? If not, this issue will be closed.

**Comment by Liubaituo** [comment]
@lzchen 
this is my test code .
--------

import logging
from opencensus.ext.azure.log_exporter import AzureLogHandler, AzureEventHandler
INSTRUMENTATION_KEY = 'key'
EXTRA_INFO = dict(custom_dimensions= dict(info="This is test"))
logger = logging.getLogger(__name__)
logEvent = logging.getLogger(__name__)

azureEventHandler = AzureEventHandler(
        connection_string=f'InstrumentationKey={INSTRUMENTATION_KEY}')
azureEventHandler.setLevel(logging.ERROR)
logEvent.addHandler(azureEventHandler)

azureLogHandler =AzureLogHandler(
    connection_string=f'InstrumentationKey={INSTRUMENTATION_KEY}')
azureLogHandler.setLevel(logging.INFO)

logger.addHandler(azureLogHandler)
logger.setLevel(logging.INFO)


def main():
    for i in range(10):
        logger.debug(str(i) + ":logger  debug Info Log", extra=EXTRA_INFO)
        logger.info(str(i) + ":logger  info Info Log", extra=EXTRA_INFO)
        logEvent.debug(str(i) + ":logEvent  debug Info Log", extra=EXTRA_INFO)
        logEvent.error(str(i) + ":logEvent  error Info Log", extra=EXTRA_INFO)


if __name__ == "__main__":
    main()
-----
I face the same problem. How can I solve it？

**Comment by lzchen** [comment]
Closing for now. Feel free to reopen if issue persists.
