### ISSUE TITLE
Traces not getting logged in azure app insights

### ISSUE THREAD

**Issue by Dhanushprabhakar** [census-instrumentation/opencensus-python#1030]
We are trying to log the traces in fast api using open census python , but the traces are not getting logged. only the requests are getting logged, through the middleware. Please help us resolve this issue

------------------------------------------------------------------------------------------------------------------------------------------

Please find the below code to reproduce the issue.

import logging
import uvicorn
from fastapi import FastAPI, Depends, Request
from opencensus.trace.samplers import ProbabilitySampler
from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.trace.tracer import Tracer
from opencensus.trace.span import SpanKind
from opencensus.trace.attributes_helper import COMMON_ATTRIBUTES

app = FastAPI()

HTTP_URL = COMMON_ATTRIBUTES['HTTP_URL']
HTTP_STATUS_CODE = COMMON_ATTRIBUTES['HTTP_STATUS_CODE']

logger = logging.getLogger(__name__)
logger.addHandler(AzureLogHandler(connection_string=f'InstrumentationKey={app_insights_key}'))
logger.setLevel(logging.INFO)

@app.middleware("http")
async def middlewareOpencensus(request: Request, call_next):
tracer = Tracer(exporter=AzureExporter(connection_string = f'InstrumentationKey={app_insights_key}'), sampler = ProbabilitySampler(1.0))
with tracer.span("main") as span:
        span.span_kind=SpanKind.SERVER
        response = await call_next(request)
        tracer.add_attribute_to_current_span(attribute_key = HTTP_STATUS_CODE, attribute_value=response.status_code)
        tracer.add_attribute_to_current_span(attribute_key=HTTP_URL,attribute_value=str(request.url))
return response

@app.get('/')
def base():
                logger.info("API running!")

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8080, debug = True)

------------------------------------------------------------------------------------------------------------------------------------------

**Comment by lzchen** [comment]
@Dhanushprabhakar 

Are you able to see logs without the `AzureLogHandler`? Can you take a screenshot?

**Comment by Dhanushprabhakar** [comment]
> @Dhanushprabhakar
> 
> Are you able to see logs normally (in your console) without the `AzureLogHandler`? Can you take a screenshot?

Yeah they are getting logged
![Uploading IMG20210512162538.jpg…]()

**Comment by Dhanushprabhakar** [comment]
> @Dhanushprabhakar
> 
> Are you able to see logs normally (in your console) without the `AzureLogHandler`? Can you take a screenshot?
Yeah they are getting logged
logger = logging.getLogger(__name__)



> @Dhanushprabhakar
> 
> Are you able to see logs normally (in your console) without the AzureLogHandler? Can you take a screenshot?
> 
> Yeah they are getting logged

logger = logging.getLogger(__name__)
logger.info("Token matched")

**Comment by RobertoPrevato** [comment]
Hi @Dhanushprabhakar 
OpenCensus and Azure Application Insights work well together, there must be something wrong in your code. If you wish to see a working example I am using, I [have one here](https://github.com/Neoteroi/Venezia/blob/dev/server/app/logs.py).

I'm using my own web framework, but the middleware concept is not different in the various web frameworks.

**Comment by RobertoPrevato** [comment]
It looks like we are doing the same things to configure OpenCensus with Azure Application Insights, it seems the only difference is that your code doesn't have:

```python
config_integration.trace_integrations(["logging"])
```

In my case, `logger.info` gets logged under App Insights traces logs.
