### ISSUE TITLE
How to change span name in SQLAlchemy extension?

### ISSUE THREAD

**Issue by RobertoPrevato** [census-instrumentation/opencensus-python#1037]
Hi,
I would like to change the `span` name in SQLAlchemy extension, to be the SQL query being executed.

Because I would like to have a report like this one from Azure Application Insights (this [I made myself using spans and raw `asyncpg` connections](https://github.com/Neoteroi/Venezia/blob/dev/server/data/pg/logs.py), note how queries are listed separately):

![image](https://user-images.githubusercontent.com/2576032/120084743-118cba80-c0d3-11eb-8271-87b8c0a1dade.png)

Instead of what I get when using the SQLAlchemy extension [as explained here](https://pypi.org/project/opencensus-ext-sqlalchemy/):

![image](https://user-images.githubusercontent.com/2576032/120084765-44cf4980-c0d3-11eb-9161-5202e93ca95d.png)

Which is less convenient, because all db queries are grouped into a single record in Azure Application Insights (because they all have span name == "sqlalchemy.query"); and I need to click on the single record and inspect samples to know the query being executed.

---

If this is not supported at the moment, I am willing to submit a PR - if PRs are welcome. 🙂

**Comment by lzchen** [comment]
You can modify the name on the Azure side by modifying the payload that gets sent using [telemetry processors](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#opencensus-python-telemetry-processors) instead of having to do it from the sqlalchemy side.

**Comment by RobertoPrevato** [comment]
Thanks, @lzchen! 
I didn't know about telemetry processors!

**Comment by RobertoPrevato** [comment]
I just realized I didn't come back adding an example of the code I used to obtain the desired result (formatted with `black`):

```python
def sql_alchemy_entries_by_query(envelope):
    if envelope.data.baseData.get("name") == "sqlalchemy.query":
        envelope.data.baseData["type"] = "SQLAlchemy"
        envelope.data.baseData["name"] = envelope.data.baseData["properties"][
            "sqlalchemy.query"
        ].replace("\n", "")
    return envelope


def configure_logging(monitoring_key: str):
    handler = AzureLogHandler(
        connection_string=f"InstrumentationKey={monitoring_key}"
    )
    handler.add_telemetry_processor(sql_alchemy_entries_by_query)
    logger.addHandler(handler)
    
    # For telemetry sent with the Azure Monitor logs exporter, logs appear under traces.
    # Exceptions appear under exceptions.
    exporter = AzureExporter(
        connection_string=f"InstrumentationKey={settings.monitoring_key}"
    )
    exporter.add_telemetry_processor(sql_alchemy_entries_by_query)
    tracer = Tracer(
        exporter=exporter,
        sampler=AlwaysOnSampler(),
    )
```

Then I get different rows depending on the query - which for me is more convenient to detect issues:

![image](https://user-images.githubusercontent.com/2576032/142771741-fb2a280e-8f62-4c84-b5d3-2cedb30f8365.png)
