### ISSUE TITLE
Trace Integration of "logging" doesn't reuse existing tracer

### ISSUE THREAD

**Issue by se02035** [census-instrumentation/opencensus-python#1043]
**Describe your environment.** 
- Python v 3.6/3.7

**Steps to reproduce.**
1. Create a custom tracer instance (with some correlation ids)
1. Invoke config_integration.trace_integrations(['logging']) 
1. use this logger to create a log entry 
1. the logger/log entry will have a different correlation id that then defined tracer -> **NOK**

**What is the expected behavior?**
The opencensus logging ext contains trace_integration(tracer=None). But the parameter "tracer" is not used. If it is set the execution context should be updated with that tracer. That ensures the internally used TraceLogger instance will use the correct correlation ids (defined by the tracer instance)

**What is the actual behavior?**
Specified tracer instance is ignored. therefore, some predefined correlation ids are used. Which obviously are wrong -> log entries can be correlated anymore. 

**Additional context.**
This is an actual problem when using the opencensus extension for Azure Functions. The Azure Function extension creates a custom tracer for e.g. tracking incoming requests & dependencies. The correlation information is required to correlated these calls. Since of the bug in the logging component e.g. error log entries can be correlated with the rest of the Azure Function log information.

**Comment by lzchen** [comment]
I'm a bit confused as to the issue. When a `Tracer` is created, it is set as the current [tracer](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/tracer.py#L89) already so subsequent log records should have their records enriched with trace data.

**Comment by se02035** [comment]
Sorry for the missing details (and creating confusion). I think at the end it comes down execution order of the code. I mean the trace integration (`config_integration.trace_integrations(['logging'])`) has to happen before the logger instance is created (which sometimes is not clear when a logger instance is created a the module level (which will be execute on import). 

Since the trace integration replaces the logging's logger class (TraceLogger) it makes more sense to be me now. I guess, that caused my confusion; a azure log entry is still created but with not trace information (since I didn't have the TraceLogger). 

I guess the only way to avoid that anyone else taps in to the same pitfall is updating the doc (or providing a very simple sample).

But since you asked this is a short sample (explaining the issue):

module globals.py
```python
def getLogger(
    name: str,
    instrumentation_conn_string: str = INSTRUMENTATION_KEY,
    propagate: bool = False,
) -> Logger:
    """Get a new logging instance with a handler to send logs to Application Insights

    Args:
        name([str]): [The name of the logger]
        instrumentation_conn_string([str]): [The AppInsights instrumentation connection string]
        propagate([bool]): [Enable log propagation (default: false)]
    """
    logHandler = AzureLogHandler(connection_string=instrumentation_conn_string)
    logHandler.add_telemetry_processor(callback_add_role_name)

    logger = logging.getLogger(name)
    logger.addHandler(logHandler)
    logger.propagate = propagate

    return logger
```

module sample_a.py
```python 
from .globals import getLogger

# problem: this logger instance gets created before the trace integration has been configured
logger = getLogger(__name__)

def log_error():
    try:
        assert 1 == 0
    except Exception as ex:
        logger.exception(ex)
    )

```

module function_entry.py
```python

from opencensus.trace import config_integration
from .sample_a import log_error

config_integration.trace_integrations(["logging"])

OpenCensusExtension.configure(connection_string=INSTRUMENTATION_KEY)

def main(req: func.HttpRequest, context: func.Context) -> func.HttpResponse:
    """Azure Function entry point
    """
    logger.info("Python HTTP trigger function processed a request.")

    # creates an exception log record with empty correlation id
    log_error()

    return func.HttpResponse(
        "This HTTP triggered function executed successfully.",
        status_code=200,
    )
```

Since I think since the system works as designed (an incorrect usage of the API), I'll close the issue again.
Thanks for your support!
