### ISSUE TITLE
Azure Event Handler is losing logs on application insight overload

### ISSUE THREAD

**Issue by urucoder** [census-instrumentation/opencensus-python#1045]
**Problem**

We are using AzureEventHandler to restore a logs backup from an old environment. 
Specifically, we have a parquet with around 8.5 million rows which are being processed in batches.
We discovered the issue with the ingestion endpoint overload and tried the timeout solution suggested [here](https://github.com/census-instrumentation/opencensus-python/issues/1007#issuecomment-770284563).
Even though we know there is a retry of the failed messages as suggested [here](https://github.com/census-instrumentation/opencensus-python/issues/1007#issuecomment-771042737), it's also failing in some way. Because at the end of the process the folder created at /tmp by opencensus was empty but not all our logs were uploaded.

**Environment** 

- Platform: Ubuntu 18.04
- Python: 3.8.10
- Packages: 
- - opencensus==0.7.13
- - opencensus-context==0.1.2
- - opencensus-ext-azure==1.0.8

**Steps to reproduce.**

After some tests, we discovered that the issue happens after 200k logs.
Script code
```
import logging
import time

import pandas as pd
from opencensus.ext.azure.log_exporter import AzureEventHandler

if __name__ == "__main__":
    in_key = input("Please insert instrumentation key: ")

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    handler = AzureEventHandler(connection_string=f"InstrumentationKey={in_key}",
                                queue_capacity=200500, timeout=30.0)
    logger.addHandler(handler)

    example = {'bool_value': [True for x in range(200001)],
               'str1': ['str1' for x in range(200001)],
               'str2': ['str2' for x in range(200001)],
               'time': ['2010-10-12T00:16:51.143000' for x in range(200001)],
               'str3': ['str3' for x in range(200001)],
               'int64': [1 for x in range(200001)],
               'str4': ['str4' for x in range(200001)]}
    df = pd.DataFrame(example)
    print(
        f"Writing {df.shape[0]} logs to the insight, {time.strftime('%H:%M:%S', time.localtime())}")
    batches = [df.iloc[i:i+500] for i in range(0, df.shape[0], 500)]
    for batch in batches:
        # Using pandas apply function overload insight, using itertuples to be less performant
        for log in batch.itertuples():
            access_data = {'custom_dimensions':
                           {'str1': log.str1,
                            'intval': log.int64,
                            'str2': log.str2,
                            'str3': log.str3,
                            'str4': log.str4,
                            'boolval': log.bool_value,
                            'time': log.time}}
            logger.info('Access log', extra=access_data)
        # workaround to avoid memory overflow in big datasets and reduce endpoint overload
        while not handler._queue._queue.empty():
            time.sleep(handler.export_interval/4)
        del batch
    print(f"Finished at {time.strftime('%H:%M:%S', time.localtime())}")
```

**What is the expected behavior?**

All logs should be uploaded even when the first try fails due to an endpoint overload

**What is the actual behavior?**

The endpoint is being overloaded and some logs are being lost

**Additional context.**

Adding some screenshots to show the test results, you will see a difference of 3 hours between the print from the script and the query in the insight because the server is in UTC and I was executing it on UTC-3

![Screenshot_20210629_175116](https://user-images.githubusercontent.com/37780362/123868547-3ceb0b00-d906-11eb-89e2-8cdd719c1e08.png)
![Screenshot_20210629_175215](https://user-images.githubusercontent.com/37780362/123868562-407e9200-d906-11eb-8b46-178a945dcec6.png)
![Screenshot_20210629_175238](https://user-images.githubusercontent.com/37780362/123868572-43798280-d906-11eb-8907-5d57d751dc93.png)

**Comment by lzchen** [comment]
@urucoder 
Are you still experiencing this issue?
