### ISSUE TITLE
Upgrade opencensus-ext-stackdriver to monitoring_v3 2.* API

### ISSUE THREAD

**Issue by pingyeh** [census-instrumentation/opencensus-python#1046]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenCensus client libraries](https://github.com/census-instrumentation). If so, please [open an issue on opencensus-specs](https://github.com/census-instrumentation/opencensus-specs/issues/new) first.

**Is your feature request related to a problem?**
If so, provide a concise description of the problem.

I can not upgrade `google.cloud.monitoring_v3` library to 2.0.0 or above in my environment because of breaking changes in its API from 1.* which `opencensus-ext-stackdriver` depends on.

**Describe the solution you'd like.**
What do you want to happen instead? What is the expected behavior?

I'd love it if `opencensus-ext-stackdriver` can be upgraded to using `google.cloud.monitoring_v3` 2.* APIs.

**Describe alternatives you've considered.**
Which alternative solutions or features have you considered?

Staying with `google.cloud.monitoring_v3` 1.1.0, but it's getting less and less attractive as it has [released](https://pypi.org/project/google-cloud-monitoring/#history) 4 new minor versions in the last 9 months since 2.0.0 came out.

**Additional context.**
Add any other context about the feature request here.

**Comment by aabmass** [comment]
I'm picking this up now, but `google-cloud-monitoring` 2.x requiresPython 3.6+. So going forward, the stackdriver exporter will only support those versions.
