### ISSUE TITLE
Unable to see metrics in custom namespace

### ISSUE THREAD

**Issue by dalavayi** [census-instrumentation/opencensus-python#1057]
Hi, I am trying to log metrics to namespace='abc'.
When I check the metrics in application insights, I don't see the logged metrics coming up in the custom namespace 'abc', but I can see the logs in the log-based-metrics standard namespace, appearing immediately after the code is run. 

We also noticed that this is happening in a completely random fashion, i.e. sometimes, the metrics are coming up in the namespace, other times they are not. 

We are not able to pinpoint why this behavior is happening. 

Used the code in this issue for logging metrics along with custom properties to be filtered on [https://github.com/census-instrumentation/opencensus-python/issues/963](url) .

Please help us resolve this, at the earliest.

**Comment by lzchen** [comment]
How are you setting the namespace? Do you have a code snippet? (the issue linked above doesn't point to anything).

**Comment by dalavayi** [comment]
https://github.com/census-instrumentation/opencensus-python/issues/963#issuecomment-781960771 
this is the link which i was referring, 
please find the code snippet below:
`from opencensus.ext.azure.common import utils
from opencensus.ext.azure.common.protocol import Data, Envelope, MetricData
from opencensus.ext.azure.log_exporter import AzureLogHandler


class AzureMetricPublisher(AzureLogHandler):

    def track_metric(self, metric_name, metric_value, namespace=None, dimensions=None):
        if namespace is None:
            namespace = metric_name
        if dimensions is None:
            dimensions = {}
        self._queue.put((metric_name, metric_value, namespace, dimensions), block=False)

    def log_record_to_envelope(self, record):
        if isinstance(record, tuple):
            envelope = Envelope(
                iKey=self.options.instrumentation_key,
                tags=dict(utils.azure_monitor_context),
                time=utils.to_iso_str(),
            )
            envelope.name = 'Microsoft.ApplicationInsights.Metric'
            name = record[0]
            value = record[1]
            ns = record[2]
            dimensions = record[3]
            data = MetricData(
                metrics=[
                    {'kind': None,
                     'name': name,
                     'ns': ns,
                     'max': value,
                     'count': 1,
                     'value': value,
                     'min': value,
                     'stdDev': 0}],
                properties=dimensions
            )
            print(data)
            print("properties :" + str(data.properties))
            envelope.data = Data(baseData=data, baseType='MetricData')
            return envelope

        return super().log_record_to_envelope(record)


metric_exporter = AzureMetricPublisher(connection_string="KEY")

metric_exporter.track_metric(metric_name='test_metric',
                             metric_value=42,
                             namespace="test_domain",
                             dimensions={"test_dimension": "value_dimension"})
`
