### ISSUE TITLE
Logs getting multiple entries in Application Insights using OpenCensus from Azure Databricks

### ISSUE THREAD

**Issue by seattlenick** [census-instrumentation/opencensus-python#1067]
import logging
from opencensus.ext.azure.log_exporter import AzureLogHndler

logger = logging.getLogger(__name__)
logger.addHandler(AzureLogHandler(
    connection_string='InstrumentationKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
)
logger.warning("Sample from open census test 01")
# logger.error("Sample from open census test 02")

Here is the screenshot we are seeing multiple logs:
![image](https://user-images.githubusercontent.com/55455425/130139068-344e6b5e-0cb4-46f9-ba55-3f3df22db3de.png)

What we are expecting is 1 message per call of this function in application insights.

**Comment by lzchen** [comment]
Are you using Azure databricks notebook to run this?

**Comment by seattlenick** [comment]
Thanks for the response.  We are using Azure Databricks notebook to run this.
We have found the cause, the Classic (Resource Mode) Application Insights is causing this issue, but writing to the new Workspace-based Application Insights is not causing this issue.

**Comment by lzchen** [comment]
@seattlenick 
May I close this issue?

**Comment by seattlenick** [comment]
yes
