### ISSUE TITLE
OpenCensusServerInterceptor reports incorrect timing

### ISSUE THREAD

**Issue by wkiser** [census-instrumentation/opencensus-python#107]
There is a bug in OpenCensusServerInterceptor that causes server spans to be finished immediately. You can reproduce it by running the helloworld grpc example in examples/trace/grpc. You should see a server span with a very short execution time, for example when I run it locally with a print exporter I get:

`{'traceId': 'a8fdeb7813144b178cb4b3d3d9b8fee4', 'spans': [{'childSpanCount': 0, 'displayName': {'truncated_byte_count': 0, 'value': 'grpc_server'}, 'parentSpanId': 4417962580138865, 'startTime': '2018-01-23T16:01:17.826761Z', 'attributes': {'attributeMap': {'/component': {'string_value': {'truncated_byte_count': 0, 'value': 'grpc'}}}}, 'spanId': 7098108131070600, 'endTime': '2018-01-23T16:01:17.826771Z'}]}`

The problem is that [this line](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/ext/grpc/server_interceptor.py#L62) is being traced, but it isn't actually executing the server handler code. It just returns an RPCMethodHandler, which defers execution. 

I hacked up a [quick fix](https://gist.github.com/wkiser/d086a3f623f135265914e2b51bb722e8) that wraps the RPCMethodHandler and instruments the span when the handler is evaluated. A better solution might be to have the RpcMethodHandlerWrapper accept arbitrary callbacks, or to update grpc to have RPCMethodHandler accept callbacks natively.

Happy to submit a PR if you have a preferred approach. Thanks!

**Comment by liyanhui1228** [comment]
Hi @wkiser, thanks for reporting this issue and providing the fix! Your quick fix looks good, a PR is welcomed, I'll do the review and check it in.
