### ISSUE TITLE
Metrics exporter continuously sends same metrics to azure monitor with each export cycle

### ISSUE THREAD

**Issue by aagateuip** [census-instrumentation/opencensus-python#1070]
**Describe your environment.** Describe any aspect of your environment relevant to the problem, including your Python version

```
Python version: python 3.6

opencensus==0.7.13
opencensus-context==0.1.2
opencensus-ext-azure==1.0.8
```

**Steps to reproduce.**
When trying the sample program here https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python
```
from datetime import datetime
from opencensus.ext.azure import metrics_exporter
from opencensus.stats import aggregation as aggregation_module
from opencensus.stats import measure as measure_module
from opencensus.stats import stats as stats_module
from opencensus.stats import view as view_module
from opencensus.tags import tag_map as tag_map_module
import logging

stats = stats_module.stats
view_manager = stats.view_manager
stats_recorder = stats.stats_recorder

prompt_measure = measure_module.MeasureInt("prompts",
                                           "number of prompts",
                                           "prompts")
prompt_view = view_module.View("prompt view",
                               "number of prompts",
                               [],
                               prompt_measure,
                               aggregation_module.LastValueAggregation())
view_manager.register_view(prompt_view)
mmap = stats_recorder.new_measurement_map()
tmap = tag_map_module.TagMap()

# TODO: replace the all-zero GUID with your instrumentation key.
exporter = metrics_exporter.new_metrics_exporter(
connection_string='InstrumentationKey=<instrumentationKey>')

view_manager.register_exporter(exporter)
logging.basicConfig(
    format='%(levelname)s:%(message)s', level=logging.DEBUG)

def prompt():
    input("Press enter.")
    mmap.measure_int_put(prompt_measure, 1)
    mmap.record(tmap)
    metrics = list(mmap.measure_to_view_map.get_metrics(datetime.utcnow()))
    print(metrics[0].time_series[0].points[0])

def main():
    while True:
        prompt()

if __name__ == "__main__":
    main()
```
* Run the above program, and hit ``Enter``` only once to submit 1 metric to Azure.
* Wait for 1 minute

**What is the expected behavior?**
* Metrics exporter should send the metric to Azure only once.

**What is the actual behavior?**
```
.\metrics_sample.py
Press enter.

Point(value=ValueLong(1), timestamp=2021-08-30 15:47:30.112085)

Press enter.DEBUG:Starting new HTTPS connection (1): svc.visualstudio.com:443
DEBUG:https://svc.visualstudio.com:443 "POST /v2/track HTTP/1.1" 200 49

DEBUG:Starting new HTTPS connection (1): svc.visualstudio.com:443
DEBUG:https://svc.visualstudio.com:443 "POST /v2/track HTTP/1.1" 200 49
```
* The same metric gets posted to azure monitor every 15 seconds (export_interval) causing duplicates in Azure
* Is this by design, if so when would the metrics be dequeued? Is there a way to flush or reset the state after they are posted to Azure?

**Additional context.**
* We were looking for something along the lines of TrackMetric https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.telemetryclient?view=azure-dotnet where we want to post "point of time" metrics to Azure

**Comment by lzchen** [comment]
@aagateuip 

This is by design, metrics in OpenCensus is categorized as useful datapoints across a time interval. If you would like to only export individual events when called, you are better suited to use [logging](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/examples/logs/simple.py) instead.

**Comment by aagateuip** [comment]
@lzchen  thanks! The problem with using logging is that we want to have these data points available as Metrics, not Logs. But we were able to find a workaround from issue posted here https://github.com/census-instrumentation/opencensus-python/issues/963 that lets us post metric only once.  FYI there is also a feature request https://github.com/census-instrumentation/opencensus-python/issues/1029 (in case you want to consider it in the future)
