### ISSUE TITLE
Custom dimensions does not work with logging.LoggerAdapter

### ISSUE THREAD

**Issue by jdvor** [census-instrumentation/opencensus-python#1097]
**Describe your environment.** 

- opencensus-ext-azure 1.1.1 [opencensus_dependency_graph.txt](https://github.com/census-instrumentation/opencensus-python/files/7951867/opencensus_graph.txt)
- python 3.8.10
- Windows 10, 64bit

**Steps to reproduce.**
```python
import os
import logging
from datetime import datetime
from opencensus.ext.azure.log_exporter import AzureLogHandler
from dotenv import load_dotenv
from typing import Any, Dict

load_dotenv(dotenv_path=".env", verbose=True)

handler = AzureLogHandler(connection_string=os.environ.get("APPLICATIONINSIGHTS_CONNECTION_STRING"),
                          storage_path=r"D:\workspace\simple")


def bare_logger(name: str) -> logging.Logger:
    logger = logging.getLogger(name)
    logger.setLevel(logging.INFO)
    logger.addHandler(handler)
    return logger


def logger_with_custom_dimensions(name: str, custom_dimensions: Dict[str, Any]) -> logging.LoggerAdapter:
    logger = bare_logger(name)
    return logging.LoggerAdapter(logger, {"custom_dimensions": custom_dimensions})


# lgr = bare_logger("mylgr")
lgr = logger_with_custom_dimensions("mylgr", {"color": "red"})

i = 0
loop = True
while loop:
    i += 1

    logger_cls = lgr.__class__.__name__
    print(logger_cls)
    print(datetime.now().strftime("%T"))

    lgr.debug("debugging message %s from %s", i, logger_cls)
    lgr.info("informational message %s from %s", i, logger_cls)
    lgr.info("informational message %s from %s with custom dimensions", i, logger_cls,
             extra={"custom_dimensions": {"orderno": i, "god": "Amon Ra", "vindictive": True}})
    lgr.warning("warning message %s from %s", i)
    lgr.error("error message %s from %s", i)
    lgr.error("error message %s from %s with custom dimensions", i, logger_cls,
              extra={"custom_dimensions": {"orderno": i, "god": "Quetzalcoatl"}})
    lgr.critical("critical message %s from %s", i, logger_cls)

    cli_input = input("next? [Y/n]")
    cli_input = cli_input.strip().lower()
    loop = cli_input == "y" or cli_input == "" or cli_input == "yes"

handler.flush()
handler.close()
print("done")
```

You can check behavior with `logging.Logger` by using `bare_logger` factory method in script above. This works as expected, but same code just with `logging.LoggerAdapter` does not.

**What is the expected behavior?**
Custom dimensions `color`, `orderno` and `god` propagated to Application Insights.

**What is the actual behavior?**
Custom dimensions requested on function calls `.info` and `.error` are ignored and only adapter-level custom dimension `color` is propagated to Application Insights.

**Comment by lzchen** [comment]
`LoggingAdapter` `extra` fields actually replace `extra` fields that are passed in via the `.info` and `.error` calls so this is actually expected behavior. If you print out the `extra` fields using `StreamHandler`, you can see this behavior in action.

**Comment by jdvor** [comment]
Ok. It is surprising at best, "expected" is certainly not a word I would use in this case. Anyways, I've already written my own adapter which behaves correctly (merging extras if both are provided). So if you feel it is expected and desired behavior as-is you can close this bug report.
