### ISSUE TITLE
python how to printf Live Metrics Stream in azure-monitor?

### ISSUE THREAD

**Issue by Liubaituo** [census-instrumentation/opencensus-python#1099]
I use opencensus.ext.azure in my python code,Other indicators are printed successfully。But Live metrics modular the expected results were not shown. it show "Not available: your app is offline or using an older SDK
Live Metrics Stream shows you key metrics within seconds. Monitor your app through deployments or critical periods.
Once enabled, Live Metrics Stream looks like this. Read more or watch the video."  I want to ask  Live Metrics  Is it not enabled by default.  
    I want to konw it should how to use,can you give me  some example。
                                                                   Thanks you !

**Comment by lzchen** [comment]
@Liubaituo 
Live metrics is not supported by OpenCensus Python SDK.

**Comment by Liubaituo** [comment]
@lzchen Thank you very much,I've been bothering this problem for a long time.
