### ISSUE TITLE
Request timeout exception when sending logs from Azure ML pipeline to Application Insights

### ISSUE THREAD

**Issue by Li0425** [census-instrumentation/opencensus-python#1104]
**Environment**
- Python version==3.6.2
- opencensus==1.1.1
- azureml-core==1.21.*

**Steps to reproduce.**
I followed this guide exactly: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-log-pipelines-application-insights

**What is the expected behavior?**
I expect to see logs being sent to Application Insights. When I query 'traces', there should be output

**What is the actual behavior?**
No traces. The error:
`[stderr]Request time out. Ingestion may be backed up. Retrying.
`

**Additional context.**
This warning message is configured here in the opencensus (line 90-93): https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/common/transport.py
I would like to know if we have run into an authentication error, and if so how to resolve it. Thanks!

**Comment by lzchen** [comment]
@Li0425 

Are you getting no telemetry at all? Could you paste a code snippet of exactly how you are using OpenCensus? (I realize you are following the guide but it would be still helpful to see the code).

**Comment by Li0425** [comment]
@lzchen 

Hello, thanks for the prompt reply! Indeed, I'm getting no telemetry at all. (I query traces in Application insights but there is no output).
```
from azureml.core import Workspace, ComputeTarget, Environment
from azureml.core.conda_dependencies import CondaDependencies
from azureml.core.runconfig import RunConfiguration
from azureml.pipeline.core import Pipeline
from azureml.pipeline.steps import PythonScriptStep

ws = Workspace.from_config()
compute_name = "cpu-vm-mlops"
compute_target = ComputeTarget(workspace=ws, name=compute_name)

myenv = Environment.from_conda_specification(name = "myenv", file_path = "env.yml")
run_config = RunConfiguration()
run_config.environment = myenv

run_config.environment.environment_variables = {
    "APPLICATIONINSIGHTS_CONNECTION_STRING": '<my_connection_string>'
}

sample_step = PythonScriptStep(
        script_name="sample_step.py",
        compute_target=compute_target,
        runconfig=run_config
)

pipeline = Pipeline(workspace=ws, steps=[sample_step])
pipeline.submit(experiment_name="Logging_Experiment")
```

sample_step.py is as follows:
```
from opencensus.ext.azure.log_exporter import AzureLogHandler
import logging
import azureml.core


print(azureml.core.__version__)

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())

logger.addHandler(AzureLogHandler())
logger.warning("I will be sent to Application Insights")
```

env.yml:
```
name: app_insights_env
dependencies:
  - python=3.7.*
  - pip

  - pip:
      - azureml-core==1.21.*
      - opencensus-ext-azure
```

**Comment by Li0425** [comment]
Hi, my colleague helped solve this issue - it's related to a rule to the VNet setting.
