### ISSUE TITLE
calling handler.close() from different thread causes deadlock when using AzureLogHandler

### ISSUE THREAD

**Issue by csadam** [census-instrumentation/opencensus-python#1125]
**Describe your environment.**
Python 3.8.13 on Linux, opencensus-ext-azure == 1.1.4, azureml-sdk[automl] ~= 1.42.0, azureml-mlflow==1.42.0, mlflow-skinny==1.26.0

**Steps to reproduce.**
I can't give an exact test code. The problem is related to #1112.
We add an AzureLogHandler on the main thread. Then later we run automl Experiment in multiple threads.

The code in the thread at some point runs `import mlflow`, and the program stucks.

The import causes to run [`_configure_mlflow_loggers(root_module_name=__name__)`](https://github.com/mlflow/mlflow/blob/aa2d955e10d0c19ed80dab1b7ccef7517ba15634/mlflow/utils/logging_utils.py#L60), which then runs the `logging.config.dictConfig`

This runs [_clearExistingHandlers](https://github.com/python/cpython/blob/6d4927ad1383e8bb8bda6659d24b6d05094a7b99/Lib/logging/config.py#L536) in logging.config, and inside of this, the [shutdown](https://github.com/python/cpython/blob/6d4927ad1383e8bb8bda6659d24b6d05094a7b99/Lib/logging/__init__.py#L2111) function runs.
The shutdown runs the following calls for all defined logging handlers:
```python
   h.acquire()
   h.flush()
   h.close()
```

With previous versions, for example opencensus-ext-azure == 1.1.3 the program stuck at the h.flush() call. 
With the 1.1.4 version the h.flush() finishes, but then the run still stops when the [self._worker.stop(timeout)](https://github.com/census-instrumentation/opencensus-python/blob/94e49eca17aa6ce2bdb121aa18e612cd7b0e8f27/contrib/opencensus-ext-azure/opencensus/ext/azure/log_exporter/__init__.py#L97) is called inside the h.close().

**What is the expected behavior?**
The import finishes successfully and the program continues

**What is the actual behavior?**
The program stops in deadlock

**Comment by jorgenader** [comment]
had similar issue. resolved it by patching handler close to add sentinel guard for timeout and use default automatically - it was freezing when `timeout = None`.


versions used also.
Python 3.9 on Linux, opencensus-ext-azure == 1.1.4, Django==3.2, django-dramatiq == 0.10.0, django-periodiq == 0.2.0

**Comment by csadam** [comment]
I'm using the following monkeypatch as workaround, but I don't think this is the "correct" way to solve this problem.

```python
    ### AzureLogHandler deadlock workaround
    #def close(self, timeout=None):
    def close(self, timeout=20.0):
        if self.storage:
            self.storage.close()
        if self._worker:
            self._worker.stop(timeout)

    from opencensus.ext.azure.log_exporter import BaseLogHandler    
    BaseLogHandler.close = close
    ###
```

**Comment by lzchen** [comment]
@jorgenader 
Are you referring to [this](https://github.com/census-instrumentation/opencensus-python/pull/1112#issuecomment-1074221126)?

**Comment by lzchen** [comment]
@csadam 
Ideally, we would use the sentinel pattern as described [here](https://github.com/census-instrumentation/opencensus-python/pull/1112#issuecomment-1074221126) to avoid breaking changes, and then remove the custom [atexit](https://github.com/census-instrumentation/opencensus-python/blob/94e49eca17aa6ce2bdb121aa18e612cd7b0e8f27/contrib/opencensus-ext-azure/opencensus/ext/azure/log_exporter/__init__.py#L67) hook in place of logging [shutdown](https://github.com/python/cpython/blob/main/Lib/logging/__init__.py#L2233).

**Comment by jorgenader** [comment]
> @jorgenader Are you referring to [this](https://github.com/census-instrumentation/opencensus-python/pull/1112#issuecomment-1074221126)?

Yes, but more like adding default timeout instead.
