### ISSUE TITLE
opencensus-ext-azure: what is the purpose of statsbeat_metrics and how it can be disabled

### ISSUE THREAD

**Issue by prabdeb** [census-instrumentation/opencensus-python#1151]
**Describe your environment.**

* opencensus-ext-azure 1.1.6
* Python 3
* Azure

**Steps to reproduce.**

In a restricted environment, where all Egress traffic requests are  exposed to a region/set-of-ips, we are seeing errors due to `westus-0.in.applicationinsights.azure.com`, where the Azure Application Insights is hosted in other region (sovereign clouds). 

**What is the expected behavior?**

Egress requests to be made only to the region/specific-resource where Azure Application Insights is hosted.

**What is the actual behavior?**

Egress requests were being made to `westus-0.in.applicationinsights.azure.com`, which is not mentioned anywhere.

**Additional context.**

* What kind of stats are being sent: as we can see [statsbeat_metrics.py](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/statsbeat/statsbeat_metrics.py), we are interested to know what kind of stat it sends to `westus-0.in.applicationinsights.azure.com`
* How to disable it: we have tried to set `APPLICATIONINSIGHTS_STATSBEAT_DISABLED_ALL` to `true` and after that application started working. But we didn't find any documentation around this, is this the right settings to disable?
* Is it possible to make the stats disabled by default?

**Comment by lzchen** [comment]
Here's the documentation on [statsbeats](https://docs.microsoft.com/en-us/azure/azure-monitor/app/statsbeat?tabs=eu-python%2Cjava).

> How to disable it

The environment variable is currently the only way to disable it.

> Is it possible to make the stats disabled by default?

There is currently no plan to do this.

**Comment by lzchen** [comment]
Will be closing the issue for now. Feel free to comment if there's any other questions.

**Comment by prabdeb** [comment]
Thanks for the response @lzchen I have created an issues in Azure Doc to make the Python part updated.
