### ISSUE TITLE
TypeError: bases must be types

### ISSUE THREAD

**Issue by aayushsin** [census-instrumentation/opencensus-python#1162]
google-api-core released a new version recently on September 2nd which is 2.10.0. The latest version install protobuf version > 4 which does not work with latest version of opencensus-ext-azure. 

**Steps to reproduce.**
Install google-api-core and opencensus-ext-azure

**What is the expected behavior?**
Imports should work fine

**What is the actual behavior?**
```bash
  File "opencensusmonitor.py", line 3, in <module>
    from opencensus.ext.azure.log_exporter import AzureLogHandler
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/opencensus/ext/azure/log_exporter/__init__.py", line 34, in <module>
    from opencensus.ext.azure.metrics_exporter import statsbeat_metrics
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/opencensus/ext/azure/metrics_exporter/__init__.py", line 31, in <module>
    from opencensus.metrics import transport
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/opencensus/metrics/transport.py", line 20, in <module>
    from opencensus.trace import execution_context
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/opencensus/trace/__init__.py", line 15, in <module>
    from opencensus.trace.span import Span
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/opencensus/trace/span.py", line 32, in <module>
    from opencensus.trace import status as status_module
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/opencensus/trace/status.py", line 15, in <module>
    from google.rpc import code_pb2
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/google/rpc/code_pb2.py", line 21, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
```

**Comment by lzchen** [comment]
@aayushsin 
Thanks for reporting this bug. I will be making a change shortly to adjust the version dependencies for google-apis. In the meantime, I believe you can try downgrading to v2.8.2 of `google-api-core` to unblock you.

**Comment by aabmass** [comment]
I'm not able to reproduce this in a fresh virtualenv. Below runs fine:

```sh
python3 -m venv venv
source venv/bin/activate
pip install google-api-core opencensus-ext-azure
python3 -c 'from opencensus.ext.azure.log_exporter import AzureLogHandler'
```

and `pip freeze` gives
```cfg
azure-core==1.25.1
azure-identity==1.10.0
cachetools==5.2.0
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==38.0.1
google-api-core==2.10.0
google-auth==2.11.0
googleapis-common-protos==1.56.4
idna==3.3
msal==1.18.0
msal-extensions==1.0.0
opencensus==0.11.0
opencensus-context==0.1.3
opencensus-ext-azure==1.1.7
portalocker==2.5.1
protobuf==4.21.5
psutil==5.9.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
PyJWT==2.4.0
requests==2.28.1
rsa==4.9
six==1.16.0
typing_extensions==4.3.0
urllib3==1.26.12
```

**Comment by aabmass** [comment]
Please see https://github.com/protocolbuffers/protobuf/issues/10012#issuecomment-1138667714, resolution is that this was due to bad install. Try with a fresh virtualenv and hopefully it works

**Comment by aayushsin** [comment]
Unfortunately, it still isn't working. I saw that ticket before. Seems like protobuf 4.x is not compatible with open-census version. 
Protobuf 4.x is default installation with google-api-core 2.10 which is default installation of opencensus-ext-azure.

However, if you already have protobuf 3.20, it will work like a charm. 

Can you check the protobuf version of your working installation?

**Comment by leonbravo** [comment]
same issue in Azure Synapse

**Comment by aabmass** [comment]
> Can you check the protobuf version of your working installation?

I put the full output of `pip freeze` above. It was `protobuf==4.21.5`

**Comment by aabmass** [comment]
I don't think there's anything for us to do here, you can try commenting on https://github.com/googleapis/python-api-common-protos/issues/128 but it doesn't look like folks there were able to reproduce it either.

**Comment by kottofy** [comment]
@leonbravo - we were having the same issue with Azure Synapse.

I believe this is due to a dependency conflict with the tensor packages set in the [Apache Spark pool requirements](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-32-runtime) since they are listed at 2.4.x (older versions).

Upgrading tensorflow worked for me with this requirements.txt:
```
tensorflow==2.10.0
opencensus-ext-azure==1.1.7
```

**Comment by pratap-is-here** [comment]
> @leonbravo - we were having the same issue with Azure Synapse.
> 
> I believe this is due to a dependency conflict with the tensor packages set in the [Apache Spark pool requirements](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-32-runtime) since they are listed at 2.4.x (older versions).
> 
> Upgrading tensorflow worked for me with this requirements.txt:
> 
> ```
> tensorflow==2.10.0
> opencensus-ext-azure==1.1.7
> ```

Worked like a charm in Synapse. Thanks @kottofy !
