### ISSUE TITLE
Zipkin Exporter rounds timestamps to nearest second. Why?

### ISSUE THREAD

**Issue by brian-macdonald-zonar** [census-instrumentation/opencensus-python#123]
Hello!

I'm researching using opencensus-python as a means to add tracing to applications I'm helping to develop.

One issue I noticed pretty quickly is that in the "translate_to_zipkin" method in the ZipkinExporter class, the start timestamp and durations variables exported to zipkin are rounded to the nearest second, then converted to microsecond units by multiplying by 1,000,000.  While the start and end timestamps are converted to microsecond units, they always have 6 trailing zeros regardless of the start and end date times.  Here is the code that's doing this -- noting the start_timestamp_ms and end_timestamp_ms:

>        for span in spans:
>            # Timestamp in zipkin spans is int of microseconds.
>            start_datetime = datetime.datetime.strptime(
>                span.get('startTime'),
>                ISO_DATETIME_REGEX)
>            start_timestamp_ms = calendar.timegm(
>                start_datetime.timetuple()) * 1000 * 1000
>
>            end_datetime = datetime.datetime.strptime(
>                span.get('endTime'),
>                ISO_DATETIME_REGEX)
>            end_timestamp_ms = calendar.timegm(
>                end_datetime.timetuple()) * 1000 * 1000
>
>            duration_ms = end_timestamp_ms - start_timestamp_ms

Python datetime objects can have microsecond precision.  
Zipkin metrics can also handle microsecond precision.  

To utilize the microsecond precision I wanted, I had to derive my own version of the ZipkinExporter class to override this method. So I calculated the duration as such:

>        for span in spans:
>            # Timestamp in zipkin spans is int of microseconds.
>           start_datetime = datetime.datetime.strptime(
>                span.get('startTime'),
>                ISO_DATETIME_REGEX)
>
>            end_datetime = datetime.datetime.strptime(
>                span.get('endTime'),
>                ISO_DATETIME_REGEX)
>
>            duration_ms = int((end_datetime - start_datetime).total_seconds() * 1000 * 1000)

The conversion I changed still involves multiplying by 1,000,000, but it's multiplied to a seconds float value instead of a rounded int as above.

As for setting the start timestamp, in the class I created, I have an epoch datetime constant like this. Since the current code assumes UTC date times, I'm assuming the same:

> epoch = datetime.datetime.utcfromtimestamp(0)

..and for converting the start_datetime variable to epoch microseconds, I do this:

> 'timestamp': int((start_datetime - self.epoch).total_seconds() * 1000 * 1000)

(The above conversion of a timedelta to epoch microseconds can be easily wrapped into a small static method.)

The precision of both the start timestamp and the duration in the class I created now utilizes true microsecond precision with these changes.

Is there a good reason the current code for ZipkinExporter needs to round to whole seconds before exporting?

- Brian

**Comment by felippe-mendonca** [comment]
I think that was fixed on PR #188, but still doesn't released a version with this patch

**Comment by songy23** [comment]
Obsolete.
