### ISSUE TITLE
Azure: Data drop 400: 106: Field 'parsedStack' on type 'ExceptionDetails' is of incorrect type. Expected: array

### ISSUE THREAD

**Issue by mark-at-kluster** [census-instrumentation/opencensus-python#1231]
**Describe your environment.** 
```
Python 3.11
opencensus==0.11.3
opencensus-context==0.1.3
opencensus-ext-azure==1.1.11
opencensus-ext-django==0.8.0
opencensus-ext-logging==0.1.1
opencensus-ext-requests==0.8.0
```

```
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
  
         "log_to_azure_ai": {
            "level": "DEBUG",
            "class": "opencensus.ext.azure.log_exporter.AzureLogHandler",
            "connection_string": os.environ.get("APPLICATIONINSIGHTS_CONNECTION_STRING")
        },

    },
    "loggers": {
        '': {
            'handlers': [ 'log_to_azure_ai'],
            'level': 'INFO',
        }
    }
}
```

**Steps to reproduce.**
Set up logging as follows. When application hits exception, 400 returned. Asking for type Dict, type is string.

**What is the expected behavior?**
No 400 response.

**What is the actual behavior?**
400 response.

**Comment by steynvl** [comment]
Is there any update regarding this? Running into the same problem with a similar environment as described by @mark-at-kluster

**Comment by EvilClam** [comment]
Having similar issue as described by @mark-at-kluster. Hoping there is an update?

**Comment by LORDDAVID2000** [comment]
> Is there any update regarding this? Running into the same problem with a similar environment as described by @mark-at-kluster

No

**Comment by LORDDAVID2000** [comment]
No problem
