### ISSUE TITLE
Pass raw spans to exporters

### ISSUE THREAD

**Issue by wkiser** [census-instrumentation/opencensus-python#127]
Currently, span objects are converted to an intermediate json format before being sent to an exporter. As a result, there are some stackdriver specific conversions [being applied](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/span.py#L222) to all spans (such as string truncation) that may not necessarily apply to all export formats.

I am proposing to update the [base.Exporter](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/exporters/base.py#L18) emit and export methods to take a raw [span.Span](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/span.py#L28) object instead of a dict. Not only will this push stackdriver specific details to the stackdriver exporter, but it would also make the development of new exporters easier since there are less layers of conversion.

Happy to make a PR if everyone is ok with the change.

**Comment by liyanhui1228** [comment]
SGTM, this was also on my to-do list but I was distracted by other works. PR would be very much appreciated!

**Comment by bogdandrutu** [comment]
I think we should not pass directly the Span object. We should pass a SpanData object that is a read-only version of the Span.

**Comment by bogdandrutu** [comment]
I think we should not pass directly the Span object. We should pass a SpanData object that is a read-only version of the Span.

**Comment by bogdandrutu** [comment]
Sorry for double posting + closing.

**Comment by liyanhui1228** [comment]
Thanks for reminding! In Python we don't actually have strictly read-only object, we can modify it anyway. But for making the exporter safe and works well in concurrent, we could extract the data in `Span` object to a `SpanData` object and document that the `SpanData` is read-only.

**Comment by wkiser** [comment]
Ok, sounds good to me. I guess for starters I'll submit a PR with a new SpanData class so everyone can agree on it?

**Comment by wkiser** [comment]
@bogdandrutu @liyanhui1228 , how would you feel about using a namedtuple for SpanData? It would provide immutability but potentially at the cost of readability.

**Comment by wkiser** [comment]
@liyanhui1228 @bogdandrutu mind taking a look at #136?

**Comment by liyanhui1228** [comment]
@wkiser LGTM
