### ISSUE TITLE
Prometheus exporter implementation

### ISSUE THREAD

**Issue by jpds** [census-instrumentation/opencensus-python#137]
Hello, I'd be very keen to see a prometheus exporter for opencensus-python. I'd like to use this instead of the flask_prometheus which I currently use.

**Comment by liyanhui1228** [comment]
Hi @jpds, prometheus exporter is for stats, which is currently being implemented in progress. We only have trace exporters for opencensus-python right now, sorry for any inconvenience. I'm going to close this issue, feel free to reopen if you have more questions. Thanks!

**Comment by Amey-D** [comment]
@liyanhui1228 

>prometheus exporter is for stats, which is currently being implemented in progress

Is there an ETA for when it will be available, or an issue where I can follow along for updates?

**Comment by bogdandrutu** [comment]
@Amey-D follow this https://github.com/census-instrumentation/opencensus-python/pull/149 when merged we can add a Prometheus exporter.

**Comment by jpds** [comment]
#149 has now been merged

**Comment by skyrocknroll** [comment]
@liyanhui1228 Is Python Prometheus in progress? is there any I can track of now considering #149 is merged? 
Thanks

**Comment by skyrocknroll** [comment]
@metonov Python prometheus is supported https://opencensus.io/faq/

**Comment by MeTaNoV** [comment]
oh OK, then, this page needs to be updated somehow! :)

https://opencensus.io/exporters/supported-exporters/python/

**Comment by jpds** [comment]
Those pages are under: https://github.com/census-instrumentation/opencensus-website/tree/master/content/exporters/supported-exporters/Python

There seems to be some initial docs under https://github.com/census-instrumentation/opencensus-website/pull/388

And people might run into: https://github.com/census-instrumentation/opencensus-python/issues/349

**Comment by MeTaNoV** [comment]
thanks @jpds (Jon) for the pointers! I'll follow that closely!

**Comment by skyrocknroll** [comment]
@MeTaNoV But it is not exporting the metrics to Prometheus. :(
