### ISSUE TITLE
Permissions required?

### ISSUE THREAD

**Issue by mhindery** [census-instrumentation/opencensus-python#138]
I've switched our home-made stackdriver tracing module to the opencensus package in our flask app. That app is deployed in a container on GKE using a specific service account. Whenever I run the app locally, I can submit traces, but the same requests on GKE just timeout. I assume this is because the service account is missing some permissions and blocks on submitting traces (locally I run with my account having all of them, so nothing will block there).

I can't find in any docs which permissions should be required (and certainly since we are currently submitting traces to StackDriver, I'd think we have the correct one.).

**Comment by liyanhui1228** [comment]
Hi @mhindery, thanks for reporting! Could you please provide more information like the error message and a gist of code that you are running?

**Comment by vlinhart** [comment]
I think you need one of these

https://cloud.google.com/iam/docs/understanding-roles#stackdriver_trace_roles

**Comment by songy23** [comment]
Seems to be the same issue to https://github.com/census-instrumentation/opencensus-python/issues/293.
