### ISSUE TITLE
Stackdriver exporter uses an invalid format for SpanId (and parentSpanId).

### ISSUE THREAD

**Issue by vincent-rondot** [census-instrumentation/opencensus-python#139]
The V2 of Stackdriver API uses the following format for the SpanId:
"[SPAN_ID] is a unique identifier for a span within a trace; it is a 16-character hexadecimal encoding of an 8-byte array."
(https://cloud.google.com/trace/docs/reference/v2/rest/v2/projects.traces/batchWrite#Span)
But it seems the library is still using the format of the previous version (64-bit integer).

The impact of this issue is that if the trace is distributed among different services(potentially using different languages) communicating for ex via HTTP, the HTTP Trace context Propagator will properly decode/encode the spanId/parentSpanID, but the python library will send to stackdriver an invalid SpanId/parentSpanId, and and the chain of spans of the trace will be broken (since the ID of the span and parentSpanId will be wrong).

Note that this issue is not visible if the trace is limited to a single service.

See PR with a suggestion of the fix.

Thanks,
Rgds,
Vincent

**Comment by wkiser** [comment]
I think the core issue here is that opencensus-python does not store span ids in the format that the spec expects: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Span.md#spancontext. I'll try and make a PR to switch the span id format from an int to a 16 char hex string everywhere.

**Comment by sonmezonur** [comment]
Agreed here. Thanks for updating span id format @wkiser. I am working on integrating Jaeger and getting an assertion error for some cases while converting it to a Jaeger Instance.

`i64 requires -9223372036854775808 <= number <= 9223372036854775807)`

I think it should be also less than 64-bit(**AT MOST** 7fffffffffffffff). But currently, it may produce numbers bigger than 64-bit.

**Comment by wkiser** [comment]
Hey @sonmezonur, I think that's happening because we are just generating 8 random bytes (max 0xFFFFFFFFFFFFFFFF), which will overflow a signed int64. Since thrift does not support unsigned int64s, you might want to try shifting the converted integer over so that it will fit: `(myint >> 1) -1`

**Comment by sonmezonur** [comment]
Yes, this is the reason. The current format may overflow. Not sure OpenCensus supports unsigned integers, if not maybe we may ensure that it generates 64-bit integer in `generate_span_id() ` method and change span id pattern. However, according to specs, there is no such limitation. So, I need to handle this during conversion to Jaeger?

**Comment by liyanhui1228** [comment]
@sonmezonur Yeah as @wkiser said, shifting the integer to make it work for Thrift might be a good approach, it's hard for us to change the span id format each time we find it doesn't work well with a specific exporter.

**Comment by wkiser** [comment]
@vincent-rondot this should have been fixed by #147. Can you verify? Thanks!

**Comment by vincent-rondot** [comment]
@wkiser, Sorry for the late response.
I have tested with version 0.1.4 which contains the fix, and it is working fine now.
Thanks for your work!
Regards,
Vincent
