### ISSUE TITLE
confusing error with integrations: `requests` integration errors out but claims it supports `requests`

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-python#142]
I was just finishing connecting a polyglot API over HTTP and tried to write a Python sample but on the first run it gives me a weird error that doesn't make sense because am trying to get the `requests` package traced, but the error interestingly is
```shell
Failed to integrate module: requests, supported integrations are httplib, mysql, postgresql, pymysql, requests, sqlalchemy, google_cloud_clientlibs
```

where the incomplete code is
```python
#!/usr/bin/env python

import requests
from opencensus.trace import tracer as tracer_module
from opencensus.trace import config_integration

# Trace our HTTP requests module
integration = ['requests']
config_integration.trace_integrations(integration)

def main():
  while True:
    query = input('Content to search$ ')
    doSearch(query)

def doSearch(query):
  with tracer.span(name='py-search') as span:
    res = requests.post('http://localhost:9778/search', json={'keywords': query})

if __name__ == '__main__':
  main()
```
<img width="571" alt="screen shot 2018-03-20 at 12 15 49 am" src="https://user-images.githubusercontent.com/4898263/37640659-df59f970-2bd3-11e8-9081-72f92a1ae172.png">

Thank you!

**Comment by liyanhui1228** [comment]
Hi @odeke-em, please check whether you have installed the `wrapt` package with `pip freeze`, this is a known issue and I'll do a new release to add the `wrapt` package to the setup.py file.

**Comment by odeke-em** [comment]
Hello @liyanhui1228, thank you for that update. I'll make that update after work and see how it goes. Otherwise I implemented a polyglot demo at https://github.com/orijtech/opencensus-demos/tree/master/media-search whose purpose is to trace HTTP requests from various clients and export them to various backends such as Stackdriver, AWS X-Ray and so far it works. However, it is my side project in the evenings after work :)

**Comment by odeke-em** [comment]
Using wrapt worked, thank you @liyanhui1228! No more warnings :)

**Comment by liyanhui1228** [comment]
@odeke-em The demo looks cool! I'm going to close this issue, feel free to reach out if you have any question.
