### ISSUE TITLE
Missing support for "forced tracing"

### ISSUE THREAD

**Issue by gdemarcsek** [census-instrumentation/opencensus-python#159]
I think you use the trace options from StackDriver incorrectly, based on this:
https://cloud.google.com/trace/docs/support?hl=sr#how_do_i_force_a_request_to_be_traced

`o=1` should mean forced tracing, regardless of the decision of the sampler. So here:

https://github.com/census-instrumentation/opencensus-python/blob/cfcfda584ba984e6f0e89684120c1ea94271b2c9/opencensus/trace/tracer.py#L68-L77

you should probably say `or` instead of `and` but please correct me if I'm missing something. To me it's more intuitive from a developer POV to have a way to force tracing for debugging reasons when needed and otherwise use some constant sampling rate. And maybe I would rename `enabled` to `forced`. I'm happy to open PR ofc if this makes sense by first look to you

**Comment by liyanhui1228** [comment]
Hi @gdemarcsek! The sampling logic here is that if tracing is enabled based on the trace options in the trace ID got from the request headers (say if we deploy a flask app on AppEngine Flex), we will consult our sampler to see whether this request should be sampled or not. But if the trace options is 0 which means this request should not be traced, we don't need to consult the sampler in this case. If we change `and` to `or` here, we would respect the sampler more than the trace option, which is not correct. And by default the trace option is 1 in the trace ID that generated by GFE, so the sampler will not have any effect if we use `or` here.

**Comment by gdemarcsek** [comment]
@liyanhui1228 Thanks, I see, but that's my point, if you have a probability sampler that takes priority over the trace options from the header, then you really cannot force tracing a request for the sake of debugging, instead, you would have to either make several requests so that the sampler eventually decides to sample yours or change the sampler to sample with `1.0` probability, but then of course, it will sample all other requests, not just the one you want to explicitly trace. The other aspect is service-to-service calls. The downstream service must know about the sampling decision of the upstream service and respect that so that the trace continues down the call tree. And I'm guessing the sampling decision is propagated through the trace option value from the X-Cloud-Trace-Context header.

If you look at the PHP instrumentation they follow the logic I'm proposing:

https://github.com/census-instrumentation/opencensus-php/blob/77e75c84851dd9a977924bee711bdef23110ca9f/src/Trace/RequestHandler.php#L102

If tracing is explicitly disabled from the header, then of course do not trace. Otherwise respect the trace option from the header - if that says trace, then trace, otherwise consult the sampler.

(that's because it's testing for explicit falseity, while it sets the enabled attribute to null in case the trace option is missing from the header): 
https://github.com/census-instrumentation/opencensus-php/blob/32468e5cc3e1b6135c968a414f7d043b33699872/src/Trace/Propagator/CloudTraceFormatter.php#L47

**Comment by wkiser** [comment]
I think what @gdemarcsek is saying is correct. Right now, I don't think the probability sampler implements the logic from the [spec](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Sampling.md#what-kind-of-samplers-does-opencensus-support) with regards to ensuring that child spans of sampled spans are also sampled. You can see this logic implemented in opencensus-go [here](https://github.com/census-instrumentation/opencensus-go/blob/master/trace/sampling.go#L55) and [here](https://github.com/census-instrumentation/opencensus-go/blob/master/trace/trace.go#L79), which I understand to be the reference implementation.

I *think* the confusion here is that the lower bit of the trace options is supposed to mean `is_sampled`, not `enabled`.

**Comment by liyanhui1228** [comment]
Thanks @gdemarcsek and @wkiser for the clarification! Changing the `and` to `or` probably is the easiest way to fix this? I'll prepare a PR for it.
