### ISSUE TITLE
Make exporters global

### ISSUE THREAD

**Issue by wkiser** [census-instrumentation/opencensus-python#173]
Both the opencensus-go and opencensus-java implementations use the pattern of registering exporters globally. I think it makes sense to do this in python as well since it should help reduce the complexity of the `Tracer` class and most middlewares. We could probably also use this as an opportunity to support multiple exporters.

Happy to submit a PR if this seems reasonable

**Comment by liyanhui1228** [comment]
Is this going to be removing the exporter from tracer and setting/getting the list of exporters from thread_local?

**Comment by liyanhui1228** [comment]
SGTM, PR is welcomed, thx!
