### ISSUE TITLE
Trace name when using python interceptors

### ISSUE THREAD

**Issue by snktagarwal** [census-instrumentation/opencensus-python#177]
I am using the interceptors (as in the hello_world_server.py) example. I am able to see the traces come through, but I am not able to get the URI for the trace right. It shows up as `grpc_server`. How do I make it look more like `com.company.name.service.RPCFunction` like? When using `go` this was automagically happening without us having to write any custom code on interceptors side.

Any guidance appreciated.

**Comment by liyanhui1228** [comment]
Hi @snktagarwal, we have updated the server interceptor to get the URI for the trace in a recent PR(#152) by @wkiser. I'll do a new release shortly to make the feature available on Pypi. Meanwhile you could install opencensus package from source to use that feature. Thanks!

**Comment by liyanhui1228** [comment]
Closing the issue, feel free to reopen if you have any questions.

**Comment by snktagarwal** [comment]
Can you tell the eta for the release? A day or a week :-)?
