### ISSUE TITLE
New Exporter for Azure Application Insights

### ISSUE THREAD

**Issue by sandeep6189** [census-instrumentation/opencensus-python#213]
Creating a new issue to gather feedback from the community. @SergeyKanzhelev @avanigupta

Trying to build a new exporter for Azure Application Insight. It requires a simple parser to convert the SpanData object to the required Request format for the Azure AI. Following is a simple program which does it:

![image](https://user-images.githubusercontent.com/3809539/42007514-742cc9f6-7a35-11e8-9aa4-fe937a2e6c27.png)

Please let me know your feedback :)

**Comment by mikaelsnavy** [comment]
Is there any work in progress on this issue, @sandeep6189 (or @SergeyKanzhelev)? I need this for a project and would love to take a stab at it. 😸

**Comment by bogdandrutu** [comment]
@mikaelsnavy you can give a try following this instructions https://docs.microsoft.com/en-us/azure/application-insights/opencensus-python?toc=/azure/azure-monitor/toc.json

**Comment by mikaelsnavy** [comment]
@bogdandrutu I already have that up and working in a multi-container App Service application, however it's not as clean as I would hope it would be. 😄 My hope was to add the exporter naively to clean up our app and deployment, if that aligns with the direction of the repo owners and existing contributors.

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev from MS can give you more details 👍

**Comment by songy23** [comment]
IIUC now we're using https://github.com/census-instrumentation/opencensus-python/tree/master/opencensus/trace/exporters/ocagent for exporting spans to Azure Monitor. Feel free to reopen if there're any further questions.
