### ISSUE TITLE
setup.py: incompatible google-api-core version with google-cloud-python/bigquery

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-python#214]
I have been nstrumenting the Google BigQuery Python package with OpenCensus but on trying to run the tests, I am encountering version problems
```shell
google-cloud-bigquery 1.3.0 has requirement google-api-core<2.0.0dev,>=1.0.0,
but you'll have google-api-core 0.1.4 which is incompatible.
```
where our version is 
https://github.com/census-instrumentation/opencensus-python/blob/93dff7302056f5cc8260d8a93c764838ce06ee9f/setup.py#L24-L26

but theirs is https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ebf80815f17b2f9878b6bdca753f60ca1fdd22ae/bigquery/setup.py#L33
<img width="773" alt="screen shot 2018-06-27 at 10 35 58 pm" src="https://user-images.githubusercontent.com/4898263/42015059-7f01b4d4-7a5a-11e8-969a-92fab3e34da6.png">

Perhaps we could bump our version?

Any piece of advice to resolve this problem would be very much appreciated!

**Comment by songy23** [comment]
Closing since we've upgraded the Google Cloud versions in new releases. Feel free to reopen if the problem persists.
