### ISSUE TITLE
Stats: TagMap has two maps

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-python#228]
One is [self._map](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/tags/tag_map.py#L24), the other is [self.tags](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/tags/tag_map.py#L26).

**Comment by zeako** [comment]
Being fixed at #248

**Comment by songy23** [comment]
Fixed in #248.
