### ISSUE TITLE
examples/helloworld/stats: cannot find modules "stats" or "tags".

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-python#243]
From [gitter](https://gitter.im/census-instrumentation/Lobby):

> I have just a quick (and maybe a basic) question...but, I'm trying to run the stats example for python on the Helloworld folder (opencensus-python/examples/stats/helloworld).

> But, after run main.py file the error "ImportError: No module named stats" is displayed because of "opencensus.stats" import. I saw the same import problem when I tried to import "opencensus.tags". However, for the trace import (opencensus.trace) everything is ok.

> Should I have to config something in my environment to work properly? Or something wrong with repo? Thanks in advance.

For me, I didn't run into this issue on my Ubuntu workstation. It looks like both users were trying to run the hello world example on MacOS, and they already followed the steps in https://github.com/census-instrumentation/opencensus-python#installation--basic-usage.

/cc @maurojcs @MarceloAquino7

**Comment by liyanhui1228** [comment]
I haven't release the stats and tags package yet as there are still bugs need to be fixed. To use it, we can build the package from source using the below commands:
```
git clone https://github.com/census-instrumentation/opencensus-python.git
cd opencensus-python
python setup.py bdist_wheel
pip install dist/*
```

**Comment by songy23** [comment]
Thanks!
