### ISSUE TITLE
Duplicate spans from requests integration

### ISSUE THREAD

**Issue by benjaminjkraft** [census-instrumentation/opencensus-python#244]
If you set up the requests integration, you get two nested spans for each call to e.g. `requests.get`/`requests.post`.  I believe this is because opencensus wraps both `Session.request` and `requests.get`/`requests.post`/etc.: if I remember correctly in (nearly?) all cases the latter calls into the former, so we get one span from each.

Just in case it's relevant: I'm running into this on Python 3.6, Ubuntu 18.04, and I see it with both the `PrintExporter` and `StackdriverExporter`.

**Comment by reyang** [comment]
Duplicate with #627.

**Comment by c24t** [comment]
Let's track it there.
