### ISSUE TITLE
ModuleNotFoundError: No module named 'google.cloud*'

### ISSUE THREAD

**Issue by hvent90** [census-instrumentation/opencensus-python#260]
Making this issue so future Python developers scratching their heads will have a solution:

After debugging for hours to get a simple [trace](https://github.com/orijtech/opencensus-for-grpc-python-developers) to run, here was the fix:

1. Remove all pip modules (you could probably get away with only removing all google cloud related modules)
2. Install `grcpio-tools`, `opencensus`, and `google-cloud-trace`

```
[WARNING: REMOVES ALL PIP MODULES] sudo pip3 freeze | sudo xargs pip3 uninstall -y
python3 -m pip install grpcio-tools opencensus google-cloud-trace
```

There are two issues out in the wild that are causing this:

* Installations of google cloud python libraries (such as `gcloud` or `google-cloud`) cause other `No Module named 'google.cloud.*'` errors
* I can't find any online documentation mentioning that google-cloud-trace is needed.

Having mention of `google-cloud-trace` on the README.md would be helpful.

Cheers!

**Comment by stewblr** [comment]
I submitted a [pull request](https://github.com/census-instrumentation/opencensus-python/pull/262) to document this since I encountered the same issue.

**Comment by odeke-em** [comment]
Great, thank you @hvent90 for filing this issue and @stewblr for the fix!
