### ISSUE TITLE
Requests instrumentation does not use standard http attributes

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-python#269]
https://github.com/census-instrumentation/opencensus-python/blob/ae727954bd03af9db768ba44721e7436be0b768f/opencensus/trace/ext/requests/trace.py

it uses `requests/url` and `requests/status_code`  attributes.

Here is the list of standard attributes:
https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/HTTP.md#attributes

**Comment by songy23** [comment]
I think this makes sense, this also matched [Go](https://github.com/census-instrumentation/opencensus-go/blob/db4ae14dbe46ab8ee97944bd6114a7e4161ee771/plugin/ochttp/trace.go#L33-L39) and [Java](https://github.com/census-instrumentation/opencensus-java/blob/50b0e198702022ffd887416f6550f0218982bb15/exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java#L91-L99). For language-specific attributes like  '/django/user', I think it's also better to follow the same naming convention.

/cc @bogdandrutu
