### ISSUE TITLE
all: fix name mangling of fields that provide property access, prefixing with `__` instead of just `_`

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-python#278]
So reading through the code in this repository, I've noticed a pattern, say
```python
class Foo:
    def __init__(self):
         self._max = 10
    @property
     def max():
         return self._max
```

of which then the recommend pattern of access is
```python
f = Foo()
f.max
```

The intention seems to be to provide information hiding and privileged access.

However, that's fallacious in code, because in Python, name mangling i.e. the best attempt at "private" access is provided by `__` as a prefix and not `_` for name mangling https://www.python.org/dev/peps/pep-0008/#id47

In the above code sample which seems to be the entire codebase's pattern, we can in fact still access the `_` prefixed field trivially by
```python
f = Foo()
f._max
```

Now, the problem here is that we are adding a seemingly unnecessary level of indirection with the `@property` decorator to a field that is basically trivially accessible by its direct name, hence adding more runtime complexity and reducing speed.

If we want to keep information hiding and "private" access, perhaps let's prefix fields with `__` instead of `_` for example
```python
class Foo:
    def __init__(self):
         self.__max = 10
    @property
     def max():
         return self.__max
```

```python
f = Foo()
f.max
f.__max # This will fail
f.Foo__max # They can still access it since Python doesn't really have private access but here that's a deliberate attempt
```

**Comment by c24t** [comment]
> Now, the problem here is that we are adding a seemingly unnecessary level of indirection with the `@property` decorator to a field that is basically trivially accessible by its direct name, hence adding more runtime complexity and reducing speed.

I agree that hiding attrs and exposing them as properties is largely pointless, especially when the properties are mutable objects themselves. In the spirit of "all being consenting adults" I think the right solution is to remove the property decorators instead of resort to name mangling.
