### ISSUE TITLE
plans to support stats

### ISSUE THREAD

**Issue by flixr** [census-instrumentation/opencensus-python#280]
Are there currently any plans to support stats as well?

In particular in a combination with a prometheus exporter...

**Comment by songy23** [comment]
Hi @flixr , at this point I believe the Python Stats library itself is done. By "itself", I mean currently you should be able to define measures/record measurements/aggregate measurements by views/get aggregated stats in process, as illustrated in the [helloworld example](https://github.com/census-instrumentation/opencensus-python/blob/master/examples/stats/helloworld/main.py).

For Stats exporters, there are a few outstanding PRs: one for updating the Stats library for better transport support (https://github.com/census-instrumentation/opencensus-python/pull/256) and one for Stackdriver Monitoring exporter (https://github.com/census-instrumentation/opencensus-python/pull/250). We plan to implement the Prometheus exporter after finishing those PRs.

/cc @MarceloAquino7 @maurojcs

**Comment by songy23** [comment]
Obsolete - Stats is already released.
