### ISSUE TITLE
file_exporter: how to dump data every x minutes

### ISSUE THREAD

**Issue by nskalis** [census-instrumentation/opencensus-python#281]
Hi,

I would be interested in using the `file_exporter` to dump the instrumentation metrics that the `opencensus` library provides, every 1 min or so.

That is useful in case you have multiple instances of the same process on the same or different host (for example, you can differentiate between them using the hostname or the pid).
If I were to use the `prometheus` exporter that would need a separate port number for each process, which is something obviously you cannot work with.

This request is inspired by the `pycounters` library here https://bitbucket.org/bleskes/pycounters/src/2db4d3b706c82e9f44b29dd24cca6eeead00d941/src/pycounters/base.py?at=default&fileviewer=file-view-default

It creates a thread that according to the defined schedule it dumps the instrumentation metrics.
Which is a very nice decoupled (from the backend) mechanism to report the instrumentation metrics, 
without forcing you to explicitly call the reporting of the metrics, which is not always possible when you loop forever and very very often.

Would you be so kind to advise if this is supported or what is the equivalent way of achieving the same using `opencensus` ?

**Comment by c24t** [comment]
Now that we've moved to poll-based metrics the file exporter (and every other exporter) does work this way. Feel free to reopen this for discussion if the behavior on master isn't what you'd expect.
