### ISSUE TITLE
Google Cloud client libraries integration does not work with Google Cloud Functions

### ISSUE THREAD

**Issue by stewblr** [census-instrumentation/opencensus-python#283]
When I use the config_integration with 'google_cloud_clientlibs' in a function deployed to Google Cloud Functions, I see the following error message in Stackdriver Logging: `Failed to integrate module: google_cloud_clientlibs, supported integrations are httplib, mysql, postgresql, pymysql, requests, sqlalchemy, google_cloud_clientlibs`.

I'm not sure what is causing this issue since we don't output the actual error message [here](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/config_integration.py#L40).

[This repository](https://github.com/stewblr/google-cloud-functions_python_trace) is a test case and includes instructions on setting up/deploying to Cloud Functions. The test case works fine in a local environment but when deployed, I don't get HTTP/gRPC traces.

**Comment by liyanhui1228** [comment]
Thanks for filing this! This is a known issue that the `wrapt` dependency is not included, will fix it in the next release.

**Comment by songy23** [comment]
Closing, `wrapt` is added in https://github.com/census-instrumentation/opencensus-python/blob/c51320d07e3c253373db20389401e8022e4278c0/setup.py#L22.
