### ISSUE TITLE
Move proto-generated files to OpenCensus-Proto.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-python#318]
I'm new to the dependency management in Python so this may be a naive question:

For the OC-Agent Exporter, we put the proto-generated Python files as a vendor under [opencensus/trace/exporters/gen/opencensus](https://github.com/census-instrumentation/opencensus-python/tree/master/opencensus/trace/exporters/gen/opencensus). AFAIS this is not convenient since every time when we made a new release on [OpenCensus-Proto](https://github.com/census-instrumentation/opencensus-proto), those gen-files need to be updated separately. This has also caused some trouble with Pylint before (https://github.com/census-instrumentation/opencensus-python/pull/266#issuecomment-418474228).

If possible, I think a better way is to host the generated Python files on [OpenCensus-Proto](https://github.com/census-instrumentation/opencensus-proto), release them as separate Python library, and have the OC-Agent Exporter import it. Note that Go [already did it](https://github.com/census-instrumentation/opencensus-proto/tree/master/gen-go).

/cc @lmolkova @liyanhui1228

**Comment by liyanhui1228** [comment]
That sounds good to me. Stackdriver Trace exporter also uses the same strategy, we host the auto-gen stackdriver trace Python files in [google-cloud-python/trace](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/trace), and release it to PyPI as google-cloud-trace library. Then it is used in stackdriver trace exporter.
