### ISSUE TITLE
No git tag for version 0.1.6 and 0.1.7 

### ISSUE THREAD

**Issue by tgermain** [census-instrumentation/opencensus-python#321]
Hi,

According to https://pypi.org/project/opencensus/#history version 0.1.6 and 0.1.7 are available on PyPi.

If I'm not mis-reading the [release process ](https://github.com/census-instrumentation/opencensus-python/blob/master/RELEASING.md), their are no git tag associated with those versions. Which make it hard for users to know what is in those versions without reading git log.

**Comment by songy23** [comment]
Closing - with the new release and change log I believe this is resolved.
