### ISSUE TITLE
Memory usage grows when using StackdriverExporter for Flask app

### ISSUE THREAD

**Issue by Amey-D** [census-instrumentation/opencensus-python#334]
I am using opencensus-python library to trace requests to my Python Flask application.

I have noticed that when using a `StackdriverExporter` instance, the memory usage of my app grows steadily for each traced request.  When observed using `memory_profiler`, the memory usage grows roughly 700KB to 1MB per request.  I have also noticed similar usage growth on GKE metrics dashboard when running the app on GKE.

All other factors being the same, if I use a `LoggingExporter` instance (instead of `StackdriverExporter`), the memory usage stays constant (as expected).

I have put together a sample app along with commands to repro this issue: https://gist.github.com/Amey-D/ebbf7acb77446e81998cf325c7737e73

Any ideas?

**Comment by c24t** [comment]
Hi @Amey-D, thanks for the detailed issue. I can reproduce this, and I'm surprised to see the same issue with both sync and async transports. I noticed that the async transport code was creating some uncollectable objects while looking into other bugs in the stats package, may be related.

**Comment by c24t** [comment]
Reproducing the issue using your example, plotting memory usage with `mprof`, making one request a second for 120 seconds.

Without opencensus middleware:

![no_middleware](https://user-images.githubusercontent.com/43799105/48097393-a4407380-e1ce-11e8-8eaa-4374d2681c40.png)

With the middleware enabled, using the `LoggingExporter`:

![logging_exporter](https://user-images.githubusercontent.com/43799105/48097830-c686c100-e1cf-11e8-8af1-760bf5283b96.png)


Using the `StackdriverExporter`:

![with_middleware](https://user-images.githubusercontent.com/43799105/48097414-ae627200-e1ce-11e8-9034-60416344445e.png)

Using the `StackdriverExporter` from an old version of the opencensus package (from 811d190):
![with_old_middleware_811d190](https://user-images.githubusercontent.com/43799105/48097446-c0441500-e1ce-11e8-89d4-8e6e20f4ae76.png)

This leak is at least as old as #92, and seems to have gotten worse over time.

**Comment by c24t** [comment]
After installing an old version of the package and reinstalling from master I can't reproduce this anymore. This suggests the leak was in another package -- maybe one of the google cloud packages -- but I don't see any obvious recent changes that would have caused this.

After wiping the env and reinstalling memory usage stays constant (at around 70MB), tested with 2.7.10 and 3.7.0.

![py2_newenv](https://user-images.githubusercontent.com/43799105/48102898-00f95980-e1e2-11e8-835b-49f7085f2207.png)

![py3_newenv](https://user-images.githubusercontent.com/43799105/48102938-1f5f5500-e1e2-11e8-948a-89fbcd936ce3.png)

@Amey-D which versions of these packages are you using? I'm on:

```
google-cloud-core==0.28.1
google-cloud-monitoring==0.29.0
google-cloud-trace==0.17.0
```

The rest of my environment is at https://gist.github.com/c24t/cc76c8499fb1be0f1b0ae9ae6bc7ebc9, I'm interested to know if you can still reproduce this with the same package versions.

**Comment by c24t** [comment]
@Amey-D FYI someone on cloud platform reports that a memory leak in the 0.1.7 release was [fixed in 0.1.8](https://github.com/GoogleCloudPlatform/microservices-demo/issues/4). I don't know that this is the same issue since you opened this after the 0.1.8 release, but if it's consistent with the problem being an old version of a dependency.

**Comment by Amey-D** [comment]
Thanks @c24t for investigating this.  Per your suggestion I upgraded the version of `opencensus-python` package to 0.1.8, and I no longer see the memory leaks.  
![flask_app_with_stackdriver_exporter_0 1 8](https://user-images.githubusercontent.com/10554902/49006888-200b5b80-f190-11e8-82e3-3cba642faece.png)

Side notes:
1. I had to add `opencensus-python[stackdriver]==0.1.8` to my requirements.txt file because the newer version treats stackdriver exporter as an extra functionality.
2. I also had to install `grpcio` separately because apparently the transitive dependency is not handled correctly by the package dependencies.

**Comment by c24t** [comment]
Reports of this bug's death may have been exaggerated. After adding OC instrumentation to the [GCP microservices demo app](https://github.com/GoogleCloudPlatform/microservices-demo), I'm seeing GKE containers leaking memory. This only happens with the stackdriver exporter, and seems to happen regardless of the transport and sampler.

<img width="1589" alt="screen shot 2018-11-21 at 1 04 02 pm-1" src="https://user-images.githubusercontent.com/43799105/49041402-fa735780-f179-11e8-94df-9965bf25bb7c.png">

I don't know if it's worth reopening yet, but I'm looking into it now and will let you know what I find.

**Comment by c24t** [comment]
We've got a fix for the memory leak in https://github.com/googleapis/google-cloud-python/pull/6856.
