### ISSUE TITLE
Improved Tracing for stand alone client applications

### ISSUE THREAD

**Issue by sduskis** [census-instrumentation/opencensus-python#366]
We're working on getting traces for stand-alone client applications in https://github.com/googleapis/google-cloud-python. To start with, we're trying to get traces for some of our system tests for clients based on grpc architecture: https://github.com/googleapis/google-cloud-python/pull/6298.  Our expectation was that we'd see multiple traces.  Instead, we saw multiple spans in a single trace.  @liyanhui1228 suggested that this was expected behavior.  That's different from what I've seen in Java.

We would like a mechanism to configure the `Tracer` to do the following:

- If there is a parent span configure in some "context", attach grpc spans to that parent span,.
- If there isn't a parent span, then the grpc span should result in an independent trace.

@c24t was in that meeting, and suggested that I add this issue.  Adding @dinooliva as an FYI.

**Comment by sduskis** [comment]
FYI @tseaver, @crwilcox, @theacodes.

**Comment by c24t** [comment]
Fixed in #539.
