### ISSUE TITLE
Bytes type monitored resource attributes should be converted to str

### ISSUE THREAD

**Issue by liyanhui1228** [census-instrumentation/opencensus-python#367]
We should ensure the attribute value type got from the metadata server [in here](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/common/monitored_resource_util/gcp_metadata_config.py#L148) is str before adding to the span attributes.

This is breaking the tests in google-cloud-python. [(here)](https://source.cloud.google.com/results/invocations/7e4fed0f-23cd-402c-82c6-53d1f0f09957/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fstorage/log)

**Comment by c24t** [comment]
Looks like this was fixed by #365.
