### ISSUE TITLE
DRY up duplicate transport code

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#386]
#256 copied the `transports` package from `trace/` into `common/`. We now have two nearly-identical copies of the code. See [`common/transports`](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/common/transports/__init__.py) and [`trace/exporters/transports`](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/exporters/transports/__init__.py).

Before merging these we need to check that the [new default options for stats transports](https://github.com/census-instrumentation/opencensus-python/pull/385) will work for tracing.

**Comment by ocervell** [comment]
Any plans to merge the `trace/exporters/transport` and `common/transports` soon ? How do we ensure this will not break backwards compatibility ?
