### ISSUE TITLE
Readme mentions webapp2 integration with no details

### ISSUE THREAD

**Issue by colincadams** [census-instrumentation/opencensus-python#392]
It looks like there used to be a webapp2 tracer, but it was partially removed in both #97 and #149. The only existing reference is in the readme that just looks like it was missed.

It seems like this should be removed, but wanted to open an issue in case a webapp2 integration would come back in the near future? It is unclear why it was removed.

**Comment by c24t** [comment]
I don't know why it was removed in #97, but as far as I know we don't have any specific plans to support webapp2. See #393 to remove it.
