### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#403]
cc @ocervell 

We've got several significant unreleased changes on master, including #365 which fixes a bug in 0.1.8 that breaks the stackdriver exporter.

At a minimum, before releasing, we need to:
- [x] Manually check integration examples
- [x] Show that this code works to instrument the [GCP microservices demo](https://github.com/GoogleCloudPlatform/microservices-demo)
- [x] Fix #401 

Currently, we tag specific revisions on master as versioned releases. This makes it difficult to apply bugfixes (like #365) to old releases. I think we should consider using [release branches](https://nvie.com/posts/a-successful-git-branching-model/#release-branches) instead, and push minor version updates to PyPI with each new commit to a release branch.

If we move to release branches, we can release the next version as 0.2.0 and plan to release bugfixes as minor version updates (e.g. 0.2.1) while continuing development on master. @reyang, @songy23, what do you think?

**Comment by c24t** [comment]
I split the first release branch into a separate PR (#407), we can track the 0.2.0 release in this issue.

**Comment by songy23** [comment]
I believe this is fixed with https://github.com/census-instrumentation/opencensus-python/releases/tag/v0.2.0.
