### ISSUE TITLE
Tracer emits although using `AlwaysOffSampler`

### ISSUE THREAD

**Issue by cbpygit** [census-instrumentation/opencensus-python#408]
I'd expect that using `AlwaysOffSampler` the tracer is silent, but it in fact spams the console. Here is a minimal example:

```
from opencensus.trace import tracer as tracer_module
from opencensus.trace.samplers import AlwaysOffSampler

tracer = tracer_module.Tracer(sampler=AlwaysOffSampler())

with tracer.span(name='should-not-trace') as span:
    pass
```

It prints:

```
[SpanData(name='should-not-trace', context=<opencensus.trace.span_context.SpanContext object at 0x7ff7ac107978>, span_id='4ac72045f7064ac2', parent_span_id=None, attributes={}, start_time='2018-11-22T08:42:32.096948Z', end_time='2018-11-22T08:42:32.096951Z', child_span_count=0, stack_trace=None, time_events=[], links=[], status=None, same_process_as_parent_span=None, span_kind=0)]
```

Doc-string of `AlwaysOffSampler` says "Do not trace any requests". This is not what I'd expect then.

If for any reason this is the intended behavior, please suggest how I can turn tracing off completely. Thanks!

EDIT: I am on Python 3 with opencensus 0.1.5

**Comment by c24t** [comment]
I would also expect that the `AlwaysOffSampler` is in fact always off, this sounds like a bug to me.

**Comment by liyanhui1228** [comment]
The sampling decision is made by the trace option and sampler together. If the trace option is enabled(which is the default), it will trace regardless of the sampler's decision. If the trace option is turned off, it's depending on the sampler's decision. #159 has more details.

**Comment by cbpygit** [comment]
@liyanhui1228 Thank you very much for your reply. It is a bit weird, but maybe it makes sense ;)

Anyway, this piece of code still prints the span:

```from opencensus.trace import tracer as tracer_module
from opencensus.trace.samplers import AlwaysOffSampler

tracer = tracer_module.Tracer(sampler=AlwaysOffSampler())

tracer.span_context.trace_options.set_enabled(False)

with tracer.span(name='should-not-trace') as span:
    pass
```

Could you please provide a minimal example for how to disable tracing completely? Thanks.

**Comment by liyanhui1228** [comment]
Hi @cbpygit, the trace option will need to be set to False before creating the tracer. As the `should_sample` and `get_tracer`(which should return a NoopTracer if forced not tracing) runs at the time when the tracer is created and won't be updated after that. It's true that this is a little annoying to set the trace options manually, but it was for aligning with the specs. Probably we should make it easier to set the trace options though.

```
from opencensus.trace import span_context
from opencensus.trace import tracer as tracer_module
from opencensus.trace.samplers import AlwaysOffSampler

sc = span_context.SpanContext()
sc.trace_options.set_enabled(False)

tracer = tracer_module.Tracer(sampler=AlwaysOffSampler(), span_context=sc)

with tracer.span(name='should-not-trace') as span:
    pass
```

**Comment by cbpygit** [comment]
Thank you very much @liyanhui1228, this helps a lot. I guess it would be sufficient if you add this on/off switching somewhere in the Readme. Should be quite regularly needed to e.g. define an environment variable that allows for easy on/off of tracing.

**Comment by liyanhui1228** [comment]
Yep will add that to readme! I'll go ahead to close this issue and feel free to reopen if you find anything else.
