### ISSUE TITLE
Allow for pluggable execution_context implementations

### ISSUE THREAD

**Issue by ewhauser** [census-instrumentation/opencensus-python#433]
The current `execution_context` implementation is hardcoded to use a thread local implementation. Applications running under different threading paradigms, such as `asyncio` or `tornado, require a different context implementation. The only current option available to extend is to monkeypatch the `execution_context`.

In order to provide for extensibility, the `execution_context` could delegate it's method calls to a pluggable implementation, i.e.:

```python
_execution_context_delegate = ThreadLocalExecutionContextDelegate()

def get_opencensus_tracer():
    """Get the opencensus tracer from thread local."""
    return _execution_context_manager.get_opencensus_tracer()
```

where the `ThreadLocalExecutionContextDelegate` is just an implementation of the existing `execution_context` methods. The configuration for the delegate class could either be set directly on the `execution_context` object (although having a stateful configuration method on the class seems like an anti-pattern) or by introducing a global configuration object like `config_integration`.

Happy to submit a PR with feedback on the approach.

**Comment by ewhauser** [comment]
This is related to #234.

**Comment by ewhauser** [comment]
After exploring this a bit more, it looks like the approach taken in #234 is unnecessary - at least in the case of Tornado. I've adapted `opentracing-python`'s implementation to work with OpenCensus:

https://github.com/ewhauser/opencensus-python/commit/2d6fdf62ecb62b582093bb30b4eb3758085652eb

**Comment by ewhauser** [comment]
The current approach I've taken abstracted out the retrieval of the storage of the current tracer into a method and monkey patch that method depending on the host environment:

https://github.com/dronedeploy/opencensus-python/blob/master/opencensus/trace/execution_context.py#L22

**Comment by c24t** [comment]
#588 should fix this.
