### ISSUE TITLE
Release 0.1.10 is missing commits

### ISSUE THREAD

**Issue by davewalkexpel** [census-instrumentation/opencensus-python#439]
I'm not sure how this happened, but tag/release 0.1.10 is missing commits, for example the ones between 11/29-12/15/18.

The most important one to us is #425. For the past few weeks we've been blowing through our Stackdriver Trace quota and I finally realized that it was because of this (we had to upgrade to 0.1.10 to get the #429 which fixed another problem that we had). When I hot-fixed it in our app, our usage immediately went down over 90%.

**Comment by davewalkexpel** [comment]
The big ones that have been haunting us are #425 and #429 (which was included in 0.1.10), but I don't want to speak for anyone else as to what other bug fixes are important. In future releases, will all bug fixes since the last release be included?

And while i have your attention, what's the the status of #380? Making the `_Worker` wait period configurable there would help us keep our usage within Stackdriver Trace's quota.

**Comment by c24t** [comment]
I'm willing to bet other people are being bit by the same bug, I'll do a release for #425.

> In future releases, will all bug fixes since the last release be included?

New minor (and major) versions will include everything from master at release time, and we'll keep cherry-picking bugfixes onto the release branches as needed.

I'll comment on the other issue.
