### ISSUE TITLE
server_interceptor exception logging

### ISSUE THREAD

**Issue by akefeli** [census-instrumentation/opencensus-python#444]
What is the reason for logging the exceptions in server_interceptor when calling the original behavior? This is causing exception logs to be duplicated. GRPC server already logs the exceptions properly.

It also does not play well with `context.abort`, which raises an Exception internally. 

I don't want to disable logging for the whole module in case there are exceptions caused by the module itself, but I don't see any other way. Also would it not be better if it used `logging.getLogger(__name__)` instead of root logger?

**Comment by c24t** [comment]
The line in question: https://github.com/c24t/opencensus-python/blob/ce97c25956f3ff6521b320e74e09c43e4ca78075/opencensus/trace/ext/grpc/server_interceptor.py#L78.

@wkiser or @liyanhui1228 may know better, but I don't see any reason to both log and raise the exception. And I agree that we shouldn't use the root logger without good reason.

**Comment by wkiser** [comment]
Yeah, I don't see any reason to not remove that line. I haven't used the python version of opencensus in a long time so I have definitely forgotten why I included that. If you send a PR, I can approve it.
