### ISSUE TITLE
Replace references to django MIDDLEWARE_CLASSES

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#451]
`MIDDLEWARE_CLASSES` has been [deprecated in favor of `MIDDLEWARE` ](https://docs.djangoproject.com/en/2.0/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware) since django 2.0. We need to scrub it from the docs, tests, and examples.

**Comment by tpyo** [comment]
This can be closed - changes were made in #694.

**Comment by reyang** [comment]
Thanks @tpyo!
