### ISSUE TITLE
Add Gauges

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#455]
The [metrics data model](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/metrics/v1/metrics.proto) includes _gauges_ for instantaneous measurements of values that increase and decrease over time.

See e.g. [gauges examples in the java client](https://github.com/census-instrumentation/opencensus-java/pull/1511/files).

Depends on #335.

**Comment by songy23** [comment]
I think gauges are done? @c24t

**Comment by c24t** [comment]
Gauges are done but not being exported yet. We can close this.
