### ISSUE TITLE
Subspans not exported for stackdriver exporter and print exporter

### ISSUE THREAD

**Issue by int8** [census-instrumentation/opencensus-python#537]
When running the code below I am not able to see **subspans** in google stackdriver trace. I am only able to see root span `span1` but no `span2` 

opencensus version is `0.2.0` (installed with pip)

```python
from opencensus.trace import tracer as tracer_module
from opencensus.trace.exporters import stackdriver_exporter
from opencensus.trace import execution_context
from opencensus.trace.samplers.probability import ProbabilitySampler

exporter = stackdriver_exporter.StackdriverExporter(project_id="myprojectid")
sampler = ProbabilitySampler(rate=1.0)
tracer = tracer_module.Tracer(sampler=sampler, exporter=exporter)


with tracer.span(name='span1') as span1:
    x = 1
    with execution_context.get_current_span().span(name="span2") as span2:
        y = 1
```

same code will produce correct results (`span1` -> `span2` visible) when using `opencensus==0.1.5`

it also occurs when using default exporter:

```python 
from opencensus.trace import tracer as tracer_module
tracer = tracer_module.Tracer()

with tracer.span(name='root') as root:
    (lambda x: x)(1)
    with root.span(name="child") as child:
        (lambda x: x)(1)
```

outputs:

```python
[SpanData(name='root',...), SpanData(name='root', ...)]
```

**Comment by int8** [comment]
I believe the problem root is here: https://github.com/census-instrumentation/opencensus-python/blob/80455edc4a461440caaa7cfd0bff873ea33a8244/opencensus/trace/tracers/context_tracer.py#L157 

where `span` is used in comprehension instead of `ss`

**Comment by int8** [comment]
it also occurs when using default exporter:

```python 
from opencensus.trace import tracer as tracer_module
tracer = tracer_module.Tracer()

with tracer.span(name='root') as root:
    (lambda x: x)(1)
    with root.span(name="child") as child:
        (lambda x: x)(1)
```

outputs:

````python
[SpanData(name='root',...), SpanData(name='root', ...)]
```

**Comment by c24t** [comment]
Thanks @int8, that looks like the problem to me too. I introduced this bug back in https://github.com/census-instrumentation/opencensus-python/pull/419, so I'm surprised that we're only seeing it now.  I'm also surprised we didn't catch this in a test.

It looks like this behavior only crops up when you create a new span with `Span.span`: `span`s created with `Tracer.start_span` get exported separately. This might explain why the bug stayed hidden for so long.

> I'm happy to contribute if given access

You should be able to fork the repo and open a PR, what other access do you need?

**Comment by int8** [comment]
> You should be able to fork the repo and open a PR, what other access do you need?
I think I tried to do it in a wrong way, thanks for fixing it though
