### ISSUE TITLE
Either provide a print or logging exporter

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-python#57]
It is giving users extensive number of options to provide both exporters. Either provide logging or printer exporter. Also, we don't expect users to depend on them other than the development time.

**Comment by liyanhui1228** [comment]
Logging exporter is for integration with Stackdriver Logging, and print reporter is for testing locally. I'd prefer to keep both of them. Closing this, feel free to reopen if there is a strong reason to remove one of them.
