### ISSUE TITLE
wrong import for stackdriver stats exporter in readme.rst

### ISSUE THREAD

**Issue by yoavMoon** [census-instrumentation/opencensus-python#578]
Wrong import in the readme example.
In opencensus-python/contrib/opencensus-ext-stackdriver/readme.rst importing stackdriver stats exporter should be:

from opencensus.stats.exporters import stackdriver_exporter as stackdriver

**Comment by c24t** [comment]
Hey @yoavMoon, that's the right import path. The exporter was moved into its own package in #556 and the old path doesn't exist anymore.

You have to install the stackdriver exporters separately as e.g. `pip install opencensus-ext-stackdriver`.

**Comment by rsalmond** [comment]
@c24t it looks like the stats exporter didn't make it into the release.

```
