### ISSUE TITLE
Memory increase due to too many traces

### ISSUE THREAD

**Issue by ChrisTerBeke** [census-instrumentation/opencensus-python#590]
Hi,

We're using this lib in several APIs running on GKE and using StackDriver. We noticed that when sending all traces to StackDriver, the amount of traces collected grows faster than the amount that can be exported to StackDriver. Because of this, a list containing all trace spans that still need to be sent grows over time, to the point where Kubernetes kills our pod because it uses too much memory.

While this is expected behavior from the current code, I wonder if there would be a cleaner way to do this. For example by dropping the spans when the list reaches a maximum and then logging a warning or error? This will prevent apps from 'leaking' memory.

What are your thoughts about this?

p.s. this is probably the same as reported on https://github.com/census-instrumentation/opencensus-python/issues/334, but it's not really resolved there.

**Comment by c24t** [comment]
Configuring samplers to have a global rate limit may help (see #458), but I agree that memory shouldn't grow unbounded by default. Dropping traces seems like a good solution to me.

As for your application: are you sampling every trace? You might want to use the [`ProbabilitySampler`](https://github.com/census-instrumentation/opencensus-python/blob/d9a74a1b44963b638e52dd26980432d969a2d520/opencensus/trace/samplers/probability.py) instead.

#334 is a different issue, the library wasn't cleaning up monitoring clients.

**Comment by c24t** [comment]
See https://github.com/census-instrumentation/opencensus-java/issues/1813 for a similar issue in the java client.

**Comment by ChrisTerBeke** [comment]
We were sampling every trace, but since then have switched to the probability sampler (which solves the problem).

Glad to hear you also think this is something to improve :)

**Comment by c24t** [comment]
@reyang's work on #642 should fix the memory issue by dropping spans once the queue is full.
