### ISSUE TITLE
Release stackdriver stats and context changes

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#597]
We've got two large breaking unreleased changes on master: making the stackdriver stats exporter consume stats as metrics (#593) and adding a context API that replaces threadlocals with contextvars on recent python versions (#588).

We'll have to release versions `0.4.0` of the core library, `0.3.0` of `opencensus-ext-stackdriver`, and `0.1.0` of `opencensus-context`. We can continue to release ext packages from the same release branch as the main library (in this case the new `v0.4.x` branch), or start using separate release branches for each package.

cc @reyang

**Comment by reyang** [comment]
Thanks for the heads up.

BTW, I have a fix #598 for the explicit context propagation (threadpool and explicit threading scenario).

**Comment by reyang** [comment]
#599 introduced the contextvars backport for Py3.6, also added test cases.

**Comment by c24t** [comment]
Among other API changes #593 changed the return type of [`new_stats_exporter`](https://github.com/c24t/opencensus-python/blob/1da32f6a2b774bc524360ea983ab1e1a2d2105bb/contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py#L368-L395) in the stackdriver exporter package.

This change may not be worth the trouble it causes since most users don't need access to the background thread that handles exporting (the method was changed to return this along with the exporter), and it forces everyone that uses the exporter to change their code. We may want to wait on changing the API until we make the same changes in the prometheus exporter, or until we have a [better strategy for announcing API changes](https://github.com/census-instrumentation/opencensus-python/issues/504). 

@reyang what do you think?

**Comment by reyang** [comment]
@c24t If we expect other breaking changes (e.g. the API change as you mentioned) in the next couple weeks, it makes sense to put the breaking changes together.

BTW, https://pypi.org/project/Deprecated/ seems to be promising.

**Comment by c24t** [comment]
Closed by #604.
