### ISSUE TITLE
Enable Threading integration 

### ISSUE THREAD

**Issue by kiarashplusplus** [census-instrumentation/opencensus-python#645]
The documentation says 'threading' integration is supported but it's not in 0.1.4.

WARNING:opencensus.trace.config_integration:Failed to integrate module: threading, supported integrations are httplib, mysql, postgresql, pymysql, requests, sqlalchemy, google_cloud_clientlibs

https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-threading

**Comment by c24t** [comment]
Please use a recent version, no guarantee that integrations will work with `0.1.4`.
