### ISSUE TITLE
Azure exporter examples are out of date 

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-python#650]
[Readme example](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/README.rst#trace)

```python
tracer = Tracer(
    exporter=AzureExporter(
        # TODO: replace this with your own instrumentation key.
        instrumentation_key='00000000-0000-0000-0000-000000000000',
        timeout=29.9,
    ),
```
does not compile

instrumentation_key should be set via options flag https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py#L45

**Comment by reyang** [comment]
This is a breaking change which hasn't been released https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/CHANGELOG.md.

* If you use the **released version from PyPi**, the document is here https://pypi.org/project/opencensus-ext-azure/ which is using Options.
* If you use the **in-development package from master**, the sample in master branch works.

In general we don't guarantee the latest in-development document/example to be compatible with a released version of package.
