### ISSUE TITLE
Implement "out-of-the-box" (OOTB) metrics for exporters

### ISSUE THREAD

**Issue by lzchen** [census-instrumentation/opencensus-python#695]
It will be valuable for users to automatically send "out-of-the-box" (OOTB) metrics easily as soon as they instrument their applications with a metrics exporter. The SDK can expose a simple way to turn these on. Necessary measures and views will be created automatically depending on the specific metric required.

We need to first define which OOTB metrics we are going to implement. IMO a good place to start would be with CPU related, memory related and requests related metrics.

**Comment by reyang** [comment]
Maintain the thread #724, #722, #720, #718.

**Comment by lzchen** [comment]
[#708]

**Comment by lzchen** [comment]
Referenced are all the "out-of-the-box" metrics currently scoped for Azure exporter. Closing this and opening an issue to address latency concerns for monkey patching request/http server libraries.
