### ISSUE TITLE
children not being added when tracer.start_span

### ISSUE THREAD

**Issue by SuyogSoti** [census-instrumentation/opencensus-python#717]
**Describe your environment.** Describe any aspect of your environment relevant to the problem, including your Python version, [platform]
python 3.7 windows

**Steps to reproduce.**
Describe exactly how to reproduce the error. Include a code sample if applicable.
```python
from opencensus.trace.tracer import Tracer
from opencensus.trace import execution_context
from opencensus.trace.samplers import AlwaysOnSampler
import time

# Initialize a tracer, by default using the `PrintExporter`
tracer = Tracer(sampler=AlwaysOnSampler())

# Example for creating nested spans
parent = tracer.start_span(name="parent")
ch1 = tracer.start_span("child")
print(ch1.parent_span.name)
print(len(parent.children))
ch1.finish()
parent.finish()
```

**What is the expected behavior?**
I expect the following to be printed.
```
parent
1
```

**What is the actual behavior?**
```
parent
0
```

**Additional context.**
None

**Comment by reyang** [comment]
Dup to #466.
