### ISSUE TITLE
opencensus-ext-azure trace_exported request.success value is always False on Python2 

### ISSUE THREAD

**Issue by arkataev** [census-instrumentation/opencensus-python#764]
* Python 2.7.13
* django==1.11.20
* opencensus == 0.7.1
* opencensus-ext-django == 0.7.0
* opencensus-ext-azure == 0.7.0

Looks like on Python2 exported request success status is wrong, because of objects comparison on [`this line`](https://github.com/census-instrumentation/opencensus-python/blob/daecc37ea3ec821b36c5a9da4094200f5a01b021/contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py#L88)

**Steps to reproduce.**
`data.success = (status_code >= 200 and status_code <= 399)`

if `status_code` type is string, than:

`>>> ("200" >= 200 and "200" <= 399)`
`>>> False `

since in python2 `int` is always less than `str`

Otherwise:
`>>> (200 >= 200 and 200 <= 399)`
`>>> True`

This mainly affects all requests `success` status displayed in Azure Monitor Log which is set to `False`

**Comment by reyang** [comment]
This is a known issue, which is being fixed by #755.

**Comment by reyang** [comment]
@victoraugustolls FYI.

**Comment by RocketPuppy** [comment]
I realize this issue is for Python2, but I think in Python3 the same issue manifests as an exception, `TypeError: '>=' not supported between instances of 'str' and 'int'`, right? Or am I encountering something else?

**Comment by reyang** [comment]
@RocketPuppy you're right.

**Comment by victoraugustolls** [comment]
@RocketPuppy yes, but the main issue is that `status code` is being sent as a `string`, but it should be ant `int`. This is fixed in #755 !

**Comment by RocketPuppy** [comment]
While that PR is in progress, is there a workaround available?

**Comment by reyang** [comment]
@RocketPuppy #755 got merged today. We will do a hotfix release. Closing the issue now.
If you cannot wait for the hotfix release, there is a way to install the package from master branch directly:
```shell
pip install "git+https://github.com/census-instrumentation/opencensus-python.git@master#subdirectory=context/opencensus-context"
pip install "git+https://github.com/census-instrumentation/opencensus-python.git@master"
# add your packages (e.g. opencensus-ext-azure) based on what's needed
...
```

@lzchen need your help to do a hotfix release. Thanks.

**Comment by RocketPuppy** [comment]
@reyang I'd like to plan when I can go live with my application monitoring in production. Do you know when that release is going to be done? I don't see anything updated on pypi or the github releases yet.
