### ISSUE TITLE
Logging django unhandled exceptions to azure, the right way

### ISSUE THREAD

**Issue by arkataev** [census-instrumentation/opencensus-python#766]
I have the following method within django middleware instance:

```
    def process_exception(self, request, 
        tracer = execution_context.get_opencensus_tracer()
              with tracer.span():
                   azure_logger.exception(exception.message)
```

this is intended to log unhandled django exceptions during request handling to `azure monitor`. The problem is that **log entities are created with `operation_Id` and `operation_ParentId` filled with `00000000000000000000000000000000`**. 

Are there any docs or the right way I can log unhandled exception and relate it to processed request? 

I have expected that **exception** `operation_ParentId` may be logged in a way to relate to **request** `operation_Id` in order to use `join`  while making query in Azure Monitor

**Comment by reyang** [comment]
@arkataev Have you enabled [**logging integration**](https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-azure#log)?

**Comment by arkataev** [comment]
Looks like I've missed that. The right way to log seems should like this:
```
# pip install opencensus-ext-logging

from opencensus.trace import config_integration

class AzureMiddleware():

def process_exception(self, request, exception):
        config_integration.trace_integrations(['logging'])
        azure_logger = logging.getLogger(__name__)
        handler = AzureLogHandler()
        handler.setFormatter(logging.Formatter('%(message)s'))
        azure_logger.addHandler(handler)
        azure_logger.exception(exception.message)
```

This allows to have exception related to request on ```operation_id```

@reyang  Thanks, for the tip!

**Comment by reyang** [comment]
Good to know.
One caveat in your code, extract the initialization code out from the `process_exception`, otherwise you will end up using more resources. The only thing that fits into `process_exception` is the following line:
```python
def process_exception(self, request, exception):
        azure_logger.exception(exception.message)
```

**Comment by afeld** [comment]
I ended up needing to tweak it for Django 4.1+:

```python
class LogErrorToAzure:
    def __init__(self, get_response):
        self.get_response = get_response
        # wait to do this here to be sure the handler is initialized
        self.azure_logger = logging.getLogger("azure")

    def __call__(self, request):
        response = self.get_response(request)
        return response

    def process_exception(self, request, exception):
        # https://stackoverflow.com/a/45532289
        msg = getattr(exception, "message", repr(exception))
        self.azure_logger.exception(msg, exc_info=exception)

        return None
```
