### ISSUE TITLE
Flask middleware raises AttributeError for 404 routes

### ISSUE THREAD

**Issue by jtbeach** [census-instrumentation/opencensus-python#777]
**Describe your environment.** 
Python 3.7, Flask 1.1, OpenCensus 0.7.3

**Steps to reproduce.**
1. Run opencensus with the Flask middleware enabled with any Flask app
2. Hit a URL that does not map to a rule (ie. `/foo`)

**What is the expected behavior?**
Don't expect exceptions thrown for 404 routes

**What is the actual behavior?**
Every 404 route is generating exceptions

**Additional context.**

The problem is caused by the following PR: https://github.com/census-instrumentation/opencensus-python/pull/759

It assumes that the url_rule is not None -- if you hit any non-existent URL (ie. a 404-triggering URL), then `request.url_rule` will be None and code will raise an `AttributeError`

**Comment by reyang** [comment]
@olance would you help on this? Thanks!

**Comment by jtbeach** [comment]
PR raised in https://github.com/census-instrumentation/opencensus-python/pull/781

**Comment by olance** [comment]
@reyang Sorry for the lag, and thanks @jtbeach for chiming in!
