### ISSUE TITLE
Application Insights - Application Map

### ISSUE THREAD

**Issue by victoraugustolls** [census-instrumentation/opencensus-python#784]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like.**
Other Applications (for example, dotNET ones) that have application insights, when they make a http request to a python app with Application Insights, the application map is globally visible. Currently the application map is not shown.

**Describe alternatives you've considered.**
None.

**Additional context.**
None.

**Comment by victoraugustolls** [comment]
Tagging @lzchen and @reyang , don't know if this is possible, but if it is, would like to contribute!

**Comment by lzchen** [comment]
@victoraugustolls Can you provide a screenshot and maybe example of what looks like?

**Comment by reyang** [comment]
@victoraugustolls There are two aspects related to this:
### Having both the .NET application and Python application speaking the same correlation language.

In OpenCensus and OpenTelemetry, the correlation protocol [by default is the W3C TraceContext](https://github.com/census-instrumentation/opencensus-python/pull/624).
In ApplicationInsights .NET SDK, the default correlation protocol is a [proprietary one](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#data-model-for-telemetry-correlation). Microsoft is working on switching to W3C TraceContext as the default correlation mechanism https://github.com/microsoft/ApplicationInsights-dotnet/pull/1193 (@cijothomas is working on this). This will happen across all SDKs for Azure Monitor / Application Insights.

With this effort, one should be able to see multiple applications using different language SDKs to work together and being correlated.
If these applications are sending data to the same ApplicationInsights instance, a full map will be available.

### Show a full Application Map across multiple ApplicationInsights instances.

There are additional challenge if two applications are sending data to different ApplicationInsights instances. Today there is a [hacky way to do this](https://github.com/microsoft/ApplicationInsights-dotnet/blob/08436e9365e65c98cb601fcda446820f72c138a6/src/Microsoft.ApplicationInsights/Constants.cs#L7) today, which is not officially documented. Microsoft is working on the backend improvement which will solve this problem (which existed for several years) by end of year 2019.

**Comment by victoraugustolls** [comment]
Thanks for the complete response @reyang , sorry for not answering sooner! Do you guys still need a screenshot?

**Comment by reyang** [comment]
I don't need a screenshot :)

**Comment by lzchen** [comment]
Refer to this [doc](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation) for how to correlate your telemetry with different SDKs. You should then be able to see your requests on App Map.
