### ISSUE TITLE
Data not sent to App Insights when run on Docker

### ISSUE THREAD

**Issue by madelineliao** [census-instrumentation/opencensus-python#785]
When running a Python module on Docker while using the Azure Monitor metrics exporter, I get an SSL error, and no data is sent to App Insights. When running the module locally, the data gets sent just fine. Not sure if it's related to [this Python issue](https://bugs.python.org/issue36137), but the workaround listed there didn't work for me.

This is the main function of the code I'm running:
```
def main():
    RUNTIME_MEASURE = measure_module.MeasureFloat("runtime", "Test runtime", "seconds")
    RUNTIME_VIEW = view_module.View("runtime_view", "Test runtime", [], RUNTIME_MEASURE, aggregation_module.LastValueAggregation())

    exporter = metrics_exporter.new_metrics_exporter(export_interval=0.5, instrumentation_key=APPINSIGHTS_INSTRUMENTATIONKEY)
    view_manager.register_exporter(exporter)

    view_manager.register_view(RUNTIME_VIEW)
    mmap = stats_recorder.new_measurement_map()
    tmap = tag_map_module.TagMap()


    """Generate the HLD for the cluster."""
    args = parse_args(sys.argv[1:])

    start_time = default_timer()

    # Generates HLD and manifests directory.
    hydrator = HLD_Generator(args)
    hydrator.generate()

    runtime = default_timer() - start_time
    mmap.measure_float_put(RUNTIME_MEASURE, runtime)
    mmap.record(tmap)
    time.sleep(0.5)
    print(f"Hydrate runtime: {runtime}")
```
This is the output I get after running `docker run` (SSL errors, followed by the normal output of the module, followed by more SSL errors):

```
docker run -v /c/Users/t-maliao/Downloads/config:/config -v /c/Users/t-maliao:/app/out hydrate.azurecr.io/hydrate:test -k /config -n hi -d -v -t

Transient client side error HTTPSConnectionPool(host='dc.services.visualstudio.com', port=443): Max retries exceeded with url: /v2/track (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)).
Transient client side error HTTPSConnectionPool(host='dc.services.visualstudio.com', port=443): Max retries exceeded with url: /v2/track (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)).
Transient client side error HTTPSConnectionPool(host='dc.services.visualstudio.com', port=443): Max retries exceeded with url: /v2/track (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)).

< normal output from the module (deleted for the sake of conciseness) >


Transient client side error HTTPSConnectionPool(host='dc.services.visualstudio.com', port=443): Max retries exceeded with url: /v2/track (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)).
Hydrate runtime: 1.8845756000373513
```

Any insight into this issue would be much appreciated! Thanks!

**Comment by lzchen** [comment]
@madelineliao 
I created a simple application that's hosted in a Windows docker image. I am able to send telemetry and see my results in Application Insights using the same instrumentation for metrics as you, so this could be a docker configuration issue. I am running a simple `docker run [image]` command.

Can you explain more about the command that you are running and what you are trying to achieve with each of the flags?

**Comment by lzchen** [comment]
@frsann 
Just to clarify, you are getting the same error messages in your logs as above?
Can you also send what command you are using to run your docker?

**Comment by frsann** [comment]
The same error, but I think I figured it out myself. I'm using PiHole Firewall on home network, and disabling it seem to have helped.

**Comment by lzchen** [comment]
@frsann 
I'm glad to hear that! If the problem comes up again, please comment on this thread again :)

**Comment by SanthoshMedide** [comment]
I am running this on **Kubernetes server** and I am not able to send the logs to **AppInsights**

----------------------------------****logging.yaml****--------------------------------------
`version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s- %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  
  null_handler:
    class: logging.NullHandler
    level: INFO

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: logs/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
  
  azure_handler:
    class: opencensus.ext.azure.log_exporter.AzureLogHandler
    level: INFO
    formatter: standard
    backupCount: 20
    encoding: utf8
    connection_string: 'instrumentation_key_here'
    timeout: 30

loggers:
  data_repo:
    level: DEBUG
    handlers: [console,info_file_handler, error_file_handler,azure_handler]
    propagate: no
  data_controller:
    level: DEBUG
    handlers: [console,info_file_handler, error_file_handler,azure_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console, info_file_handler, error_file_handler,azure_handler]`

-------------------------------**setting the logging(set_logging.py)**----------------------------
`import logging
from opencensus.ext.azure.log_exporter import AzureLogHandler

def setup_logging(
    default_path='logging.yaml',
    default_level=logging.DEBUG
):
    """Setup logging configuration

    """
    path = default_path
    print("set logging")
    if os.path.exists(path):
        with open(path, 'rt') as f:
            config = yaml.safe_load(f.read())
            config['handlers']['azure_handler']['connection_string']=cfg.APP_INSIGHTS_CONNECTION
        logging.config.dictConfig(config)
    else:
        logging.basicConfig(level=default_level)`
I am running this on **kuberntes server** and I am not able to send the logs to **AppInsights**

Here is the **ERROR**
`2020-06-14 02:00:40,986 - azure.storage.common.storageclient - INFO - Client-Request-ID=c2393a78-ae0c-11ea-9f4c-a683e7151156 Outgoing request: Method=HEAD, Path=, Query={'snapshot': None, 'timeout': None, 'restype': None}, Headers={'x-ms-version': '2018-03-28', 'User-Agent': 'Azure-Storage/1.4.2-1.5.0 (Python CPython 3.6.0; Darwin 18.7.0)', 'x-ms-client-request-id': 'c2393a78-ae0c-11ea-9f4c-a683e7151156', 'x-ms-date': 'Sun, 14 Jun 2020 07:00:40 GMT', 'Authorization': 'REDACTED'}.`

**Comment by lzchen** [comment]
@SanthoshMedide 
Tracked by: https://github.com/census-instrumentation/opencensus-python/issues/908
