### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by victoraugustolls** [census-instrumentation/opencensus-python#791]
Isn't it time for a new release? We have a bunch of new fixes merged into master, including `requests` exception propagation and `flask` middleware not crashing when rule is none.

Tagging @reyang @c24t

**Comment by lzchen** [comment]
I will be doing a new release at the end of the month.

**Comment by lzchen** [comment]
https://github.com/census-instrumentation/opencensus-python/releases/tag/v0.7.5
https://github.com/census-instrumentation/opencensus-python/releases/tag/v0.7.4
