### ISSUE TITLE
why use export rather than export_metrics

### ISSUE THREAD

**Issue by lee3164** [census-instrumentation/opencensus-python#805]
```py
    # TODO: deprecate
    def export(self, view_datas):
        """export view datas to registered exporters"""
        view_datas_copy = \
            [self.copy_and_finalize_view_data(vd) for vd in view_datas]
        if len(self.exporters) > 0:
            for e in self.exporters:
                try:
                    e.export(view_datas_copy)
                except AttributeError:
                    pass
```
this is the export method in measure_to_view_map.py, and it calls e.export, but the ocagent.stats_exporter.StatsExporter has no method export, why? below is the code of ocagent.stats_exporter.StatsExporter

```py
class StatsExporter(object):
    """Stats exporter for an opencensus metrics grpc service.

    :type rpc_handler: ExportRpcHandler
    :param rpc_handler: export rpc handler
    """

    def __init__(self, rpc_handler):
        self._rpc_handler = rpc_handler

    def export_metrics(self, metrics):
        """ Exports given metrics to target metric service.
        """
        metric_protos = []
        for metric in metrics:
            metric_protos.append(_get_metric_proto(metric))

        self._rpc_handler.send(
            metrics_service_pb2.ExportMetricsServiceRequest(
                metrics=metric_protos))
```

**Comment by lzchen** [comment]
If you take a look at the `new_stats_exporter` method in ocagent.stats_exporter, there is a line `transport.get_exporter_thread([stats.stats], exporter, interval)` in which a new thread is created to handle getting and exporting of metrics in a separate worker thread. The logic is in `get_exporter_thread` in opencensus.metrics.transport.py. The method called is the `export_metrics` method of the passed in exporter. StackDriver and Azure both use this method as well. We are trying to deprecate exporting through `export` in measure_to_view_map.py.

**Comment by lzchen** [comment]
Closing this as it seems the question is answered.
