### ISSUE TITLE
What is the right way to use Flask 

### ISSUE THREAD

**Issue by varunarora** [census-instrumentation/opencensus-python#813]
Hi!
Since the code for `opencensus-ext-azure` is hosted in this repo, posting this issue here.

**Is your feature request related to a problem?**
I have a Flask web app (which will run in a Docker container, behind `gunicorn`), and am using the Azure ecosystem. My current problem is that I am unable to capture/see the stack traces in the **Samples** interface on Azure for failures in the requests made.

![image](https://user-images.githubusercontent.com/629203/68559951-bf524e80-03f3-11ea-8c31-91b095e93ef6.png)

**Describe the solution you'd like.**
I wish to capture the request/response status AND GET and POST params. I also wish to capture and "export" the stack trace when uncaught errors happen. I wish to capture these in the Azure Application Insights / Monitor.

**Describe alternatives you've considered.**
I have configured both the `AzureExporter` (with the `FlaskMiddleware`) and `AzureLogHandler`. Requests show up with their error/success status, but none of the traces OR more detailed bodies of the requests.

**Additional context.**
I have seen documentation for Python applications on some pages, and for Flask on others. Haven't seen something that combines everything for the Azure integration, so I am just guessing things.

My code is as follows:

```python
import logging

from flask import Flask, jsonify
from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.trace import config_integration
from opencensus.ext.flask.flask_middleware import FlaskMiddleware
from opencensus.trace.samplers import ProbabilitySampler, AlwaysOnSampler

application = Flask(__name__)
connection_string = "InstrumentationKey=" + os.environ['AZ_INSTRUMENTATION_KEY']
config_integration.trace_integrations(['logging'])

middleware = FlaskMiddleware(
    application,
    exporter=AzureExporter(connection_string=connection_string),
    sampler=AlwaysOnSampler()
)

logger = logging.getLogger(__name__)
handler = AzureLogHandler(connection_string=connection_string)
handler.setFormatter(logging.Formatter('%(traceId)s %(spanId)s %(message)s'))
logger.addHandler(handler)


@application.route('/', methods=['POST'])
def index():
    # An application whose code fails for dumb miscellaneous reasons.
    return jsonify({})

if __name__ == "__main__":
    application.run(host="0.0.0.0", debug='DEBUG' in os.environ, port=1337)

```

**Comment by lzchen** [comment]
@varunarora 
Exception telemetry is only shown through the `AzureLogHandler` when an exception is logged through your application. As you have figured out, request/dependency telemetry do not show stack traces and exception data. In order to see which requests generated a specific exception, you can utilize the `logging` integration as shown in your example. This will append `trace-id` and `span-id`s to your log telemetry, and you will be able to correlate the exception data with the spans that generated them.

**Comment by varunarora** [comment]
@lzchen I don't understand 90% of that answer (I am new to the world of telemetry), but I promise I will try to infer it after doing some prerequisite reading, and get back to you. Thank you!

**Comment by lzchen** [comment]
@varunarora  No worries! Feel free to reach out if you have any questions!

**Comment by lzchen** [comment]
@varunarora Can this issue be closed?

**Comment by lzchen** [comment]
Closed due to inactivity.
