### ISSUE TITLE
please publish 0.7.7 to pypi

### ISSUE THREAD

**Issue by ctaggart** [census-instrumentation/opencensus-python#857]
We were excited to see [0.7.7 tagged](https://github.com/census-instrumentation/opencensus-python/releases/tag/v0.7.7 ), but it is still not available at
https://pypi.org/project/opencensus/ . It still has 0.7.6 published on Nov 26th. Could you please publish 0.7.7 to pypi.org? We want to update to the new version because https://github.com/census-instrumentation/opencensus-python/issues/834 is fixed.

**Comment by lzchen** [comment]
Should be fixed. Be sure to use the latest version of `opencensus-ext-azure` to get the changes as well.

https://pypi.org/project/opencensus/
