### ISSUE TITLE
Azure Exporter and AsyncIO (Starlette)

### ISSUE THREAD

**Issue by victoraugustolls** [census-instrumentation/opencensus-python#863]
I was wondering if using the Azure Exporter would be considered safe when working with asyncio / starlette (fast api). I know it has blocking calls like file system and using the request library, so was wondering if those can block the event loop when used by the exporter. 

@lzchen

**Comment by lzchen** [comment]
Support for fast api is being done in [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-python/issues/710) via ASGI integration.

Any potential issues that you may foresee can be discussed there.
