### ISSUE TITLE
Databricks sending multiple entries to app insight

### ISSUE THREAD

**Issue by rwforest** [census-instrumentation/opencensus-python#865]
**Describe your environment.** Databricks runtime 6.4 ML
**Steps to reproduce.**
log.warning()

**What is the expected behavior?**
What did you expect to see?
log one entry

**What is the actual behavior?**
What did you see instead?

multiple entries are being logged

**Additional context.**

All logging would result in multiple entries, sometimes 4 or more dups with exactly same everything.

**Comment by mcb0035** [comment]
I am also encountering this issue intermittently.

**Comment by lzchen** [comment]
Do you have a code snippet you can paste? As well as examples of pieces of telemetry you are seeing multiples of?

**Comment by rwforest** [comment]
its only log.warning, nothing special.

e.g. logger.warning(f'{dbName}.{tableName}.{i}', extra=properties)

But it seems to be ok now.

**Comment by lzchen** [comment]
Closing due to resolved.
