### ISSUE TITLE
Only warning, error, and exceptions logged; info and other loglevels not appearing in AppInsights

### ISSUE THREAD

**Issue by mcb0035** [census-instrumentation/opencensus-python#866]
**Describe your environment.** 
Local, Python 3.7.3

**Steps to reproduce.**
```
import logging
from opencensus.ext.azure.log_exporter import AzureLogHandler
logger = logging.getLogger(__name__)
handler = AzureLogHandler(connection_string='InstrumentationKey=xxxx')
logger.addHandler(handler)

logger.log(logging.INFO, 'test log')
logger.info('test info')
logger.warning('test warning')
logger.error('test error')
logger.debug('test debug')
```

**What is the expected behavior?**
All five logs appear in AppInsights

**What is the actual behavior?**
Only warning and error appear in AppInsights

**Comment by lzchen** [comment]
The root logger for the Python logging library has a logging level set to [WARNING](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel). Any logs that are below this level will not actually be logged, and as such, not sent to Application Insights.

**Comment by mcb0035** [comment]
Is this configurable?  Is there a way to at least suppress the warning to the user, so the message gets logged to AppInsights but not echoed to stdout?

**Comment by mcb0035** [comment]
Nevermind, figured it out:
    logger.setLevel(logging.INFO)

**Comment by lzchen** [comment]
Closing.
