### ISSUE TITLE
Custom Properties not working

### ISSUE THREAD

**Issue by davidychow87** [census-instrumentation/opencensus-python#869]
I've followed the example for adding custom dimensions exactly as is:

https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-azure#custom-properties

but, I don't see any of the custom keys (key_1, key_2 under the customDimensions field (under traces) in Application insights. I do see the messages, just not the custom properties.

IDE: Visual Studio Code
Python environment: 3.7.5 (.venv)

Does any one have any idea how to fix this? Thanks.

**Comment by lzchen** [comment]
What version of `opencensus-ext-azure` are you using?

**Comment by davidychow87** [comment]
It looks like it is v 1.0.2

**Comment by lzchen** [comment]
Closed and resolved offline.

**Comment by pselden** [comment]
How was this resolved? I think I'm seeing something like this for Google Cloud Trace

**Comment by lzchen** [comment]
@pselden User was running an incorrect query to find their data in the backend.
