### ISSUE TITLE
Multiple log entry in AppInsight

### ISSUE THREAD

**Issue by sharmapriyanka1502** [census-instrumentation/opencensus-python#870]
I am using this sample code for testing exception log entry in the log table. 

Code
-------------------------------------------------------------------------------
import logging
from opencensus.ext.azure.log_exporter import AzureLogHandler
import uuid

logger = logging.getLogger(__name__)

logger.addHandler(AzureLogHandler(
    connection_string='InstrumentationKey=*******************')
)

pipelineName = 'Sample Pipeline 2'
runId = uuid.uuid1()

properties = {'custom_dimensions': {'PipelineName': f'{pipelineName}', 'runId': f'{runId}', 'AlertType': 'PriyankaTesting1803Test10'}}

try:
  a = 2
  b = 'abc'
  c = a + b
except Exception:
  logger.exception('Exception example.', extra=properties) 

-----------------------------------------------------------------------------------
Observations:

When I try to dump exception logs into the table at a gap of 30 seconds, I found logs been inserted correctly. 

![correct](https://user-images.githubusercontent.com/62370963/77036132-5d72a880-69d4-11ea-93ec-ad388480d10b.png)

As soon as I started triggering the logs one after the other, I see multiple entries been dumped for the same log. Though the entry numbers i see being limited to 2 or 3 unlike last testing which maxed till 7 entries. 
![1](https://user-images.githubusercontent.com/62370963/77036155-6c595b00-69d4-11ea-8306-efb1c7ddd0ab.png)
![2](https://user-images.githubusercontent.com/62370963/77036156-6e231e80-69d4-11ea-8c06-4a7c5aa9ec33.png)
![3](https://user-images.githubusercontent.com/62370963/77036158-6ebbb500-69d4-11ea-97c6-278c3daf6e39.png)
![4](https://user-images.githubusercontent.com/62370963/77036160-6f544b80-69d4-11ea-844b-98509fc01609.png)
![5](https://user-images.githubusercontent.com/62370963/77036162-6f544b80-69d4-11ea-8183-23615e77045c.png)

-----------------------------------------------------------------------------------------------------------

**Comment by lzchen** [comment]
Can you clarify what you mean about dumping logs at a gap of 30 seconds? How are you doing this?
As well as a code snippet of the second case, how are you triggering the logs one after the other? Is the telemetry in the screenshot all from 1 log entry?

**Comment by sharmapriyanka1502** [comment]
I trigger the above mentioned code one after the other manually using databricks notebook. I see duplicate entries.
There are 5 screenshots attached, each screenshot represent duplicate entry of one log. If you check the timestamp it's repetitive.

**Comment by lzchen** [comment]
Can you check the `runid` value in `customDimensions` of the duplicate entries? That should show whether or not they are indeed duplicates or you are simply sending different log entries but within a small time frame.

**Comment by sharmapriyanka1502** [comment]
They are duplicates as runId within the custom dimensions are also same.

**Comment by sharmapriyanka1502** [comment]
Adding screenshot for reference
![image](https://user-images.githubusercontent.com/62370963/77286427-37f9dd80-6cf9-11ea-95c9-0046ee5679c8.png)

**Comment by lzchen** [comment]
@sharmapriyanka1502 

I was able to reproduce the issue using Azure databricks. I was not able to reproduce it when running as a normal Python script. It might have something to do with databricks having multiple clusters and workers and how it interacts with the logging framework. As of now, there is no support for OpenCensus integration with Azure databricks/databricks.

**Comment by sharmapriyanka1502** [comment]
Thanks for your input. We have our huge set of code written in PySpark and utilizing databricks notebook for the same. It cannot be migrated to Python script.

**Comment by lzchen** [comment]
Got it. Thanks for your feedback. I will create an issue to investigate support with Databricks :)

**Comment by rwforest** [comment]
@lzchen I have done the same test, using the below script. The issue happens within the same block of code in Databricks, not related to how often it ran.

The first time it ran it'd generate 10 entries. The second time I ran it after 3 minutes later it creates 30 entries, with everything the same.

import logging
from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.ext.azure.trace_exporter import AzureExporter

import uuid
import time

logger = logging.getLogger(__name__)
logger.addHandler(AzureLogHandler(
    connection_string='InstrumentationKey='XXXX'))

i = 0
while(True):
    pipelineName = 'Sample Pipeline'
    runId = uuid.uuid1()
    properties = {'custom_dimensions': {'PipelineName': f'{pipelineName}', 'runId': f'{runId}', 'AlertType': 'DataOpsCriticalException'}}
    logger.warning('Warning trace example.', extra=properties)
    time.sleep(1)

    i = i + 1
    if i == 10:
        break

**Comment by lzchen** [comment]
@sharmapriyanka1502 
Try clearing the state of the databricks notebook in between running the script. It seems that databricks stores something in the execution context that causes multiple log entries to be sent.

**Comment by lzchen** [comment]
See https://github.com/census-instrumentation/opencensus-python/issues/874#issuecomment-606763438

**Comment by lzchen** [comment]
@sharmapriyanka1502 
Has your questions been answered?

**Comment by sharmapriyanka1502** [comment]
Yes.

**Comment by kaykumar** [comment]
for anybody who is looking at in the future: this happens in databricks or any notebook environment because the AzureLogHandler handler is getting added to the logger multiple times, this can be prevented like this

```
logger = logging.getLogger(__name__)
 **if(not any(isinstance(x, AzureLogHandler) for x in logger.handlers)):**
    logger.addHandler(AzureLogHandler(
        connection_string='InstrumentationKey='XXXX'))
```
       
Hope that saves some time for folks in future.
