### ISSUE TITLE
[opencensus-ext-azure] logger.info() and logger.debug() not being sent to App Insights

### ISSUE THREAD

**Issue by snobu** [census-instrumentation/opencensus-python#871]
Using
```
Python 3.7.7 on macOS 10.15.3
 
opencensus-context==0.1.1
opencensus-ext-azure==1.0.2
```

`logger.info(...)` and `logger.debug(...)` do not get sent to Azure Application Insights.
Am i doing it wrong or is this a known issue?

`logger.warning(...)` for example produces the expected events in Application Insights.

To reproduce:

```python
from opencensus.ext.azure.log_exporter import AzureLogHandler

logger = logging.getLogger(__name__)
logger.addHandler(AzureLogHandler(
    connection_string="InstrumentationKey=X-X-X-X")
)

logger.info("this is info")
logger.warning("this is a warning")
logger.debug("this is debug")
logger.error("this is an error")
```
Not filtering any traces:

![image](https://user-images.githubusercontent.com/6472374/77180282-5e89ff80-6ad2-11ea-89e8-976084221ca7.png)

**Comment by lzchen** [comment]
See https://github.com/census-instrumentation/opencensus-python/issues/866.

**Comment by snobu** [comment]
Thank you for that. Should i send a PR adding this little fact to the README? I'm not sure the root logger story is that well known out there.

**Comment by lzchen** [comment]
@snobu  Yes that would be great!
