### ISSUE TITLE
When run froma running Job in databricks it is not login anything

### ISSUE THREAD

**Issue by AntonioJDios** [census-instrumentation/opencensus-python#875]
**Describe your environment.** 
If I run the the notebook step by step  I get the loggin. However if I run the complete notebook as a job triggered from databrick API it finishes before sending any log. It looks like it has not flushed. However with the applicationinsight libray I get the logged when I do manually tc.flush()

**Steps to reproduce.**
 properties = {
              'ApplicationName':application,                                
              'CustomerId': customer_id,
              'Entity_name':'Memory-Consumption',
              'Period':period, 
              'memory':str(memory),
              'Time':str(time),
              'Status_code' : str(status_code['statusCode']),
              'CalculationDate':readings_name[1], 
              'Job_id': jobId
             }

  
  extra = {'custom_dimensions': properties}
  logger.setLevel(logging.INFO)
  logger.info(info+": Run statusCode "+ str(status_code['statusCode'])+": " +customer_id, extra=extra)
**What is the expected behavior?**
What did you expect to see?
log in app insight
**What is the actual behavior?**
What did you see instead?
no log
**Additional context.**

**Comment by lzchen** [comment]
Since OpenCensus exports log telemetry to Azure Monitor asynchronously in a separate worker thread, if the main thread terminates (the main application), the logs will not be sent. Either make it so your application does not exit right away, or set the [export interval](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/common/__init__.py#L92) to be smaller (default is 15.0s)

**Comment by AntonioJDios** [comment]
Ok.. i thought that. Can I forze to flush before exiting from the thread??

**Comment by lzchen** [comment]
Yes the threads are designed to flush upon exit of the application.
If you add `sys.exit()` at the end, this should do the trick.

**Comment by rwforest** [comment]
> Yes the threads are designed to flush upon exit of the application.
> If you add `sys.exit()` at the end, this should do the trick.

@lzchen sys.exit() doesn't work in databricks

**Comment by lzchen** [comment]
What you can also do is hang the main thread so it does not exit so the telemetry has time to be exported.

`input("...")`

**Comment by rwforest** [comment]
got it, I implemented a longRunningJob function and calls it at the end

import time
def longRunningJob():
  time.sleep( 20 )

**Comment by lzchen** [comment]
Great!
