### ISSUE TITLE
Fast processes don't log everything to application insights

### ISSUE THREAD

**Issue by jelther** [census-instrumentation/opencensus-python#882]
**Describe your environment.** Python 3.6 with opencensus-ext-azure and logging integrations

**Steps to reproduce.**
Log several messages at once and kill the process after

**What is the expected behavior?**
Have all messages on Application Insights

**What is the actual behavior?**
Some messages are not logged due to execution time.

**Additional context.**
Tried to add a `time.sleep(60)` but it's not enough.

Is there a way to guarantee that all the telemetry was sent before killing the process instead of just using a time.sleep ?
Already tried to set `handler = AzureLogHandler(export_interval=1.0)` but it wasn't enough.

**Comment by lzchen** [comment]
Just to clarify, is 60.0s not enough time for all your telemetry to be exported?

**Comment by jelther** [comment]
@lzchen , not.
It's an ETL processes that sometimes took less than 30 seconds.
Since we want to use Application Insights to keep tracking what's going on, it's not enough.

**Comment by lzchen** [comment]
I am assuming you are worried about the log telemetry being lost from the 1.0s interval between the last export and the process exiting. Setting `export_interval=1.0` is as granular of reporting as you can get currently. We don't have flushing of log telemetry on application exit as of yet.

**Comment by jelther** [comment]
Ok @lzchen , thanks for your help.
Is there anything on the landscape about that (like, check if everything was sent) ?

**Comment by lzchen** [comment]
No there is no check to determine this.

**Comment by jelther** [comment]
Ok then, I'll close this issue.
