### ISSUE TITLE
AWS Lambda Error using the Azure Monitor

### ISSUE THREAD

**Issue by Ramachillara** [census-instrumentation/opencensus-python#894]
Hi Team, 

I tried to deployed an AWS lambda(python based) using opencensus-ext-azure. 
But when i try to invoke the lambda i am getting the following error. 

Not sure if the module is supported on AWS lambda for python ?, i am able to run the same program fine locally/with out AWS lambda.

Appreciate your response. 
========================================

Error.
===============================================
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/task/handler.py", line 11, in lambda_handler
    exporter=AzureExporter(
  File "/var/task/opencensus/ext/azure/trace_exporter/__init__.py", line 50, in __init__
    self.storage = LocalFileStorage(
  File "/var/task/opencensus/ext/azure/common/storage.py", line 90, in __init__
    self._maintenance_routine(silent=False)
  File "/var/task/opencensus/ext/azure/common/storage.py", line 112, in _maintenance_routine
    os.makedirs(self.path)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)END RequestId: 85daef1a-6da1-4b4d-ae70-0006faba240a

Thanks 
Ram

**Comment by lzchen** [comment]
`AzureExporter` creates a folder in your environment's home directory to store local files (telemetry that was not sent properly). It seems like your home folder in your AWS lambda env `/home/sbx_user1051` is read only so the folder cannot be created.

**Comment by kapilt** [comment]
only /tmp space is writable in lambda. its a very strange choice by the plugin to use a homedir instead of a tempdir

**Comment by lzchen** [comment]
The home directory is simply the default path, as every environment will have one, instead of a /tmp folder whose location might be specific to the infrastructure. If you want to specify which directory you want to output your local storage to, modify `storage_path` and pass it into the constructor of `AzureExporter`.

`exporter = AzureExporter(connection_string='your-connectionstring', storage_path='your-path-here')`

**Comment by Ramachillara** [comment]
I added the  /tmp variables to HOME environment variable and it worked fine.

**Comment by lzchen** [comment]
@Ramachillara 
As of [OpenCensus v0.7.8](https://github.com/census-instrumentation/opencensus-python/releases/tag/0.7.8), your local default local file store is in the OS temp folder, not your home.

**Comment by Ramachillara** [comment]
@lzchen sorry missed your other thread where you mentioned to add the storage path . I think we can close this issue if it is ok with you , i guess the below should work with out the work around i did using the HOME environment variable setting to /tmp
exporter = AzureExporter(connection_string='your-connectionstring', storage_path='/tmp')
