### ISSUE TITLE
Initializing with the "proxy" option passed in doesn't appear to work when initializaing AzureLogHandler and AzureExporter

### ISSUE THREAD

**Issue by skinamdar** [census-instrumentation/opencensus-python#896]
https://github.com/census-instrumentation/opencensus-python/blob/99821a0b826445cecce0881a01790c8cc6958ceb/contrib/opencensus-ext-azure/opencensus/ext/azure/common/__init__.py#L98

See partial sample invocation below where the proxy is passed in. 
```
from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.ext.azure.trace_exporter import AzureExporter
non_azure_https_proxy = {"https": "https://www.google.com"} # to test that the command fails
app_insights_connection_string = "insert_here"
azure_logger = AzureLogHandler(connection_string=app_insights_connection_string, proxy=azure_https_proxy)
azure_exporter = AzureExporter(connection_string=app_insights_connection_string, proxy=azure_https_proxy)
```

Running a similar command over curl 
```
curl -d '{"name": "MetricData", "time":"2020-05-29T00:18:28.9586379Z","iKey":"{insert_i_key_here}","data":{"baseType":"MetricData","baseData":{"metrics":[{"name":"Custom metric","value":2,"count":1}]}}}' https://dc.services.visualstudio.com/v2/track -x https://www.google.com -v
```
results in a curl address error (which we expect as we want to make sure the requests passed via opencensus are routed to a proxy which we've defined)

Can you please update the code to make sure it works with a custom proxy passed in?

**Comment by skinamdar** [comment]
Also proxy appears in only one line `➜  opencensus-python git:(master) grep -r "proxy" *
contrib/opencensus-ext-azure/opencensus/ext/azure/common/__init__.py:        proxy=None,`

**Comment by lzchen** [comment]
Yes `proxy` as a configuration does not do anything at the moment.

**Comment by skinamdar** [comment]
@lzchen Can the proxy functionality be enabled by the library as a bug fix?

**Comment by lzchen** [comment]
I'm tagging this as a feature request.

Please include a description of the behaviour that you want. Can you also reformat your original post so that the code sample looks more readable?

**Comment by skinamdar** [comment]
Thank you. 

Behavior description:
Please add the ability for the AzureLogHandler and AzureExporter class to use a proxy passed in by the caller to connect to its services. This is helpful when for security reasons, we prefer to use a proxy to connect to the services instead of connecting directly. This will make the class behavior consistent with invoking Application Insights requests over curl where we can pass a proxy to the request.

**Comment by skinamdar** [comment]
Hi @lzchen, I created a PR to address this feature request https://github.com/census-instrumentation/opencensus-python/pull/902. Please review when you can. Thank you!

**Comment by skinamdar** [comment]
Closing this issue as the feature request was merged.
