### ISSUE TITLE
how to add cloudRoleName and cloudInstanceName to python appinsights

### ISSUE THREAD

**Issue by chetanku** [census-instrumentation/opencensus-python#897]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenCensus client libraries](https://github.com/census-instrumentation). If so, please [open an issue on opencensus-specs](https://github.com/census-instrumentation/opencensus-specs/issues/new) first.

**Is your feature request related to a problem?**
If so, provide a concise description of the problem.
Yes, in .net and js libraries for appinsights you can add custom telemetry of cloudRolename and cloudInstancename, I don't see documentation around it for python from Microsoft.

**Describe the solution you'd like.**
What do you want to happen instead? What is the expected behavior?
Addin cloudRoleName and cloudInstanceName helps filtering different containers/vms running python microservices.
**Describe alternatives you've considered.**
Which alternative solutions or features have you considered?

**Additional context.**
Add any other context about the feature request here.

**Comment by lzchen** [comment]
See [this doc](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#opencensus-python-telemetry-processors).

`cloudRoleName` is 'ai.cloud.role'
`cloudInstanceName` is `ai.cloud.roleInstance`
