### ISSUE TITLE
Stackdriver tests failing and blocking build

### ISSUE THREAD

**Issue by lzchen** [census-instrumentation/opencensus-python#905]
See [build](https://travis-ci.org/github/census-instrumentation/opencensus-python/jobs/697381561).
Fails for Python 2.7, Python 3.4.

Removing these tests for now to unblock build.

@c24t

**Comment by skinamdar** [comment]
Thank you for doing that

**Comment by aabmass** [comment]
@lzchen can you assign me this one?
