### ISSUE TITLE
**The program runs on a Kubernetes cluster. Logs when run on local,they work. But they don't go to AppInsights Azure**

### ISSUE THREAD

**Issue by SanthoshMedide** [census-instrumentation/opencensus-python#908]
**The program runs on a Kubernetes cluster. Logs work on local but not sent to AppInsights Azure**
----------------------------------logging.yaml--------------------------------------
```
version: 1
disable_existing_loggers: False
formatters:
standard:
format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
error:
format: "%(asctime)s- %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
console:
class: logging.StreamHandler
level: DEBUG
formatter: standard
stream: ext://sys.stdout

null_handler:
class: logging.NullHandler
level: INFO

info_file_handler:
class: logging.handlers.RotatingFileHandler
level: INFO
formatter: standard
filename: info.log
maxBytes: 10485760 # 10MB
backupCount: 20
encoding: utf8

error_file_handler:
class: logging.handlers.RotatingFileHandler
level: ERROR
formatter: error
filename: logs/errors.log
maxBytes: 10485760 # 10MB
backupCount: 20
encoding: utf8

azure_handler:
class: opencensus.ext.azure.log_exporter.AzureLogHandler
level: INFO
formatter: standard
backupCount: 20
encoding: utf8
connection_string: 'instrumentation_key_here'
timeout: 30

loggers:
data_repo:
level: DEBUG
handlers: [console,info_file_handler, error_file_handler,azure_handler]
propagate: no
data_controller:
level: DEBUG
handlers: [console,info_file_handler, error_file_handler,azure_handler]
propagate: no

root:
level: DEBUG
handlers: [console, info_file_handler, error_file_handler,azure_handler]
```
-------------------------------**setting the logging(set_logging.py)**----------------------------

```
def setup_logging(
    default_path='logging.yaml',
    default_level=logging.DEBUG
):
    path = default_path
    print("set logging")
    if os.path.exists(path):
        with open(path, 'rt') as f:
            config = yaml.safe_load(f.read())
            config['handlers']['azure_handler']['connection_string']=cfg.APP_INSIGHTS_CONNECTION
        logging.config.dictConfig(config)
    else:
        logging.basicConfig(level=default_level)

```
----------------------------**my program python file**---------------------------------------
```
import traceback
import logging

logger = logging.getLogger(__name__)
def run():
   logger.info("Run started")
   try:
       access data 
   except Exception as e:
            params = {_some information in dict format_}
            logger.error("Failed to pull the data required "+str(e),exc_info=True, extra=params)
        
```
------------------------Here is the possible **ERROR**-----------------------------------------
```
2020-06-14 02:00:43,118 - data_repo - ERROR - Failed to pull the data required 'NoneType' object is not subscriptable
2020-06-14 02:43:40,986 - azure.storage.common.storageclient - INFO - Client-Request-ID=c2393a78-ae0c-11ea-9f4c-a683e7151156 
Outgoing request: Method=HEAD, Path=, Query={'snapshot': None, 'timeout': None, 'restype': None}, Headers={'x-ms-version': '2018-03-28', 
'User-Agent': 'Azure-Storage/1.4.2-1.5.0 (Python CPython 3.6.0; Darwin 18.7.0)',
 'x-ms-client-request-id': 'c2393a78-ae0c-11ea-9f4c-a683e7151156', 'x-ms-date': 'Sun, 14 Jun 2020 07:00:40 GMT', 'Authorization': 'REDACTED'}.```

All logs are working when I run them on local.
I am running application on Kubernetes 
Logs from the main file are going to ApplicationInsights (Main file runs on a pod)
While logs from the rest of the files are not going to AppInsights (All these files are on diff pod)
There's no config difference between these pods

_Originally posted by @SanthoshMedide in https://github.com/census-instrumentation/opencensus-python/issues/900#issuecomment-643732989_

**Comment by lzchen** [comment]
If you remove the AzureLogHandler, do you get the same error? It doesn't seem like the error is generated from the SDK.

**Comment by SanthoshMedide** [comment]
@lzchen ```2020-06-14 02:00:43,118 - data_repo - ERROR - Failed to pull the data required 'NoneType' object is not subscriptable```
This error is from the log.error(from my application). The real issue is it's not sending the logs to AppInsights. It says 
```'Authorization': 'REDACTED'```.

**Comment by lzchen** [comment]
When you run your application locally, with AzureLogHandler, are you able to see logs in App Insights?

**Comment by SanthoshMedide** [comment]
Yes

**Comment by lzchen** [comment]
What is within `access data`? It seems that the exception is generated within that code. Are you able to pinpoint the line that is causing this?

**Comment by SanthoshMedide** [comment]
Hi, Chen. I am trying to replicate and figure out the exact error so that I
can give you more info. I will ping you as in when I get more clarity.
Thanks for your timely replies.

>

**Comment by SanthoshMedide** [comment]
It is working fine and the issue is not from SDK. Thanks :)

**Comment by insert-piotr-jez** [comment]
I have similiar problem. What's the reason?

**Comment by apurvjain17** [comment]
Hi @SanthoshMedide 

Can you please explain what was the issue here?  We're experiencing a similar issue. What worked for you might work for us too. 

Thanks

**Comment by bruno314** [comment]
Same issue here. I've pretty much excluded all other possibilities. Logs even work on Azure Pipelines but they're magically disabled on Azure Kubernetes. Spent a lot of time excluding other options (e.g. level issue, handler not being hit, config issue, bad instrumentation key, etc.). Nothing helped. @lzchen any official resolution?

**Comment by lzchen** [comment]
@bruno314 
No official resolution from SDK side. You might have to open up a ticket with Azure Kubernetes team.

**Comment by Tejas25Jan** [comment]
az monitor app-insights query --app $ApplicationId --analytics-query $query --offset 1d | ConvertFrom-Json is failing with error.
az : ERROR: Error occurred in request., SSLError: HTTPSConnectionPool(host='api.applicationinsights.io', port=443): Max retries exceeded with url: 
/v1/apps/e*******-d***-4***-9***-51*********/query (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local 
issuer certificate (_ssl.c:997)')))
At line:6 char:17
+ ... $response = az monitor app-insights query --app $ApplicationId --anal ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Error oc..._ssl.c:997)'))):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to 
the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.
Cannot index into a null array.
At line:7 char:5
+     $impactedRows = $response.tables[0];
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
