### ISSUE TITLE
Adding atexit handler to stackdriver exporter

### ISSUE THREAD

**Issue by aravinsiva** [census-instrumentation/opencensus-python#927]
This is needed such that SIGTERM's can be handled in OpenCensus in order to publish any remaining telemetry data to the GCP backend. Currently this exists in the azure exporter but not in the stackdriver exporter.

**Describe the solution you'd like.**
Add an atexit handler to the stackdriver expoter such that remaining telemetry is flushed upon SIGTERM being handled.

**Describe alternatives you've considered.**
Currently exists in Opentelemetry however since support for OpenCensus will continue for some time it would be advantageous to include this in OpenCensus. 

The following need to be done:

- Use Async transporter as the default transporter for Stackdriver trace exporter such that the atexit handler is used by default and main thread is not blocked (Update README).

- Create atexit handler for Stackdriver metrics exporter

**Comment by aabmass** [comment]
@aravinsiva do you want me to assign this to you?

**Comment by aravinsiva** [comment]
Yes that would be great!

**Comment by aravinsiva** [comment]
Issue is currently being addressed in the above two PR's.
