### ISSUE TITLE
PR #930 causes infinite hang

### ISSUE THREAD

**Issue by tiloc** [census-instrumentation/opencensus-python#937]
**Describe your environment.** Django 2.2 with OpenCensus middleware from master branch
opencensus                            0.8.dev0 
opencensus-context                    0.2.dev0
opencensus-ext-azure                  1.0.dev0
opencensus-ext-django                 0.8.dev0
opencensus-ext-logging                0.2.dev0 

Running in an on-premise environment, trying to log to Azure. 

**Steps to reproduce.**
Add OpenCensus Middleware to settings.py
Run Django

**What is the expected behavior?**
Server starts up

**What is the actual behavior?**
Server hangs indefinitely

**Additional context.**
Root cause seems to be an attempt to reach an unreachable hard-coded IP address. 
_AIMS_URI = "http://169.254.169.254/metadata/instance/compute"

The request.get call to this address does not specify any timeout parameter, which ultimately leads to the hang.

**Comment by lzchen** [comment]
@tiloc 
Can you see if [#939] solves your issue?

**Comment by tiloc** [comment]
It does. I had previously implemented the same measure on my personal fork already. I cannot sign a CLA, otherwise my PR would have been identical to yours.
