### ISSUE TITLE
Azure Metrics Exporter data point namespace handling

### ISSUE THREAD

**Issue by gxtaillon** [census-instrumentation/opencensus-python#947]
@izchen @reyang The code mentions a todo in one of your commits but I didn't see an issue to deal with it on the repo here. 

On the Azure metrics exporter, the namespace is set to the same value as the name of the metric, this creates UX unfriendly bits in Azure App Insight when dealing with many custom metrics (eg: 50+). Has there been a conversation started on how to handle this todo? I'd like to make/get a fix for it.

https://github.com/census-instrumentation/opencensus-python/blob/8401a4542173a7bcc5dc794e607fd4165f0de66a/contrib/opencensus-ext-azure/opencensus/ext/azure/metrics_exporter/__init__.py#L103-L106

Best

**Comment by lzchen** [comment]
@gxtaillon 
Can you give an example of what you want to achieve out of the namespace?

**Comment by gxtaillon** [comment]
A namespace with more than one metric in it.

Lets say i had two different, but related metrics, I would like to be able to group them. Right now they will only ever appear as distinct namespaces.

See screenshots :

![image](https://user-images.githubusercontent.com/567119/90992041-361f9900-e57b-11ea-94fa-01e6f8b19c3d.png)

![image](https://user-images.githubusercontent.com/567119/90992067-53ecfe00-e57b-11ea-9027-5e17986abbf2.png)

**Comment by lzchen** [comment]
Right makes sense. We could possibly make the [description](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/stats/measure.py#L32) field when instantiating a metric be the namespace instead of duplicating the name.

**Comment by gxtaillon** [comment]
What`s the downside of adding a dedicated namespace field?

**Comment by lzchen** [comment]
@gxtaillon 
It would be a breaking change.

**Comment by gxtaillon** [comment]
Correct me if I'm wrong but if we use the description, there may be description usage out there in the wild that would act as the namespace and that would be a bit unexpected after an upgrade, no?

**Comment by lzchen** [comment]
@gxtaillon 
For azure metrics exporter, description does not have any function currently. It is populated simply because the definition for a measure requires it. So this would be more of a "feature addition" instead of a "change in behaviour". It also has the benefit of not breaking users' applications.

**Comment by gxtaillon** [comment]
Sorry, my bad, I should have put a reference in my previous comment. The default snippet from MS would have to be updated -- https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python#metrics and my guess is that a lot of folks are using it like that.

I also found a way to update the ns using the callback function which works out for me. I'm ok closing this issue.

```py
def callback_function(envelope):
  for m in envelope.data.baseData.metrics:
    if (m.name.startswith('X/Y/Z')):
      m.ns = 'X'
  return True

exporter = metrics_exporter.new_metrics_exporter(
    connection_string='InstrumentationKey=123',
    export_interval=1.0)
exporter.add_telemetry_processor(callback_function)
view_manager.register_exporter(exporter)
```
