### ISSUE TITLE
Exclude certain parts of code from dependency tracing

### ISSUE THREAD

**Issue by dpgrodriguez** [census-instrumentation/opencensus-python#951]
**Is your feature request related to a problem?**
We use dependency tracing and send to Azure Application insights. We import the tracer at the entry point of the code and every other class that we call thereafter also sends dependency data to App Insights.

**Describe the solution you'd like.**
Is there a way to exclude certain parts from App Insights? 
i.e.

```
class Main:
    def __init__(self):
          process1 = Process1()
          process2 = Process2()

    def process(self):
          with self.tracer(span='Main'):
                process1.process()
                process2.process()
```
Importing App insights in Main class makes Process1 and Process2 send telemetry data. Is there a way to exclude Process2 from sending data?

**Comment by lzchen** [comment]
If you are trying to exclude certain paths/hostnames from being traced and your are using flask/django/pyramid, you can add these paths to the [exclude list[(https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python-request#tracking-flask-applications) in configuration.

Same can be done for requests/httplib by the following:

```python
from opencensus.trace import execution_context

execution_context.set_opencensus_attr('blacklist_hostnames', ['http://wont-be-traced.com'])
```

**Comment by dpgrodriguez** [comment]
Cool! I'll try this. Forgive my ignorance but are the other settable attributes documented somewhere?

**Comment by lzchen** [comment]
@dpgrodriguez 
Unfortunately they are not. The opencensus docs could use some work xD

**Comment by dpgrodriguez** [comment]
That was really helpful though and found that there are some interesting things in the utils as well. Thanks!
