### ISSUE TITLE
CustomDimension not working

### ISSUE THREAD

**Issue by NaveenkumarIyappan** [census-instrumentation/opencensus-python#963]
**Describe your environment.** 
Version: python3.6
Running as a container in RHEL VM.
After importing `opencensus.ext.azure.log_exporter` docker image is built only when the Dockerfile is changed to have
`RUN yum install -y gcc  rh-python36 rh-python36-python-devel.x86_64`

**Steps to reproduce.**
**logger.py**

```
import logging
import os
from opencensus.ext.azure.log_exporter import AzureLogHandler

_azhandler = AzureLogHandler(connection_string='InstrumentationKey={}'.format(os.getenv('app_insights_instrumentation_key')))
_azhandler.setLevel(logging.DEBUG)
_azhandler.setFormatter(logging.Formatter('%(levelname)s: %(message)s'))
_azlogger = logging.getLogger('FileUploader')
_azlogger.addHandler(_azhandler)

def info_customdimension(message, customDictionary):
    try:
        _azlogger.info(message, extra=customDictionary)
        print('Sent custom dictionary log')
    except Exception:
        print('Cannot send custom dictionary log')
```

Consumer of this logger file
```
 custom_dimensions = {}
 custom_dimensions['JobId'] = job_id
 custom_dimensions['FileUpload'] = True
 custom_properties = {}
 custom_properties['custom_dimensions'] = custom_dimensions

 info_customdimension("Successfully uploaded'), custom_properties)
```

**What is the expected behavior?**
Application insights log should show custom dimensions properties along with the log message.

**What is the actual behavior?**
Application insights log shows only log message.

**Additional context.**

**Comment by lzchen** [comment]
@NaveenkumarIyappan 
Are you able to see any log messages at all in App Insights?

**Comment by NaveenkumarIyappan** [comment]
@lzchen I see only the message as `INFO: Successfully uploaded` and the default custom dimension, but not the `JobId` and `FileUpload`

**Comment by lzchen** [comment]
Strange, I'm able to get it working with the exact code, and the `custom_dimensions` show up exactly. Maybe it has something to do with running in a VM? Can you run your code just as a python file?

**Comment by raphaelauv** [comment]
I'm having the same problem with custom_metric -> https://github.com/census-instrumentation/opencensus-python/pull/820

the dimension , do not show up in azure monitor 


code to reproduce : 
```python
from opencensus.ext.azure.common import utils
from opencensus.ext.azure.common.protocol import Data, Envelope, MetricData
from opencensus.ext.azure.log_exporter import AzureLogHandler


class AzureMetricPublisher(AzureLogHandler):

    def track_metric(self, metric_name, metric_value, namespace=None, dimensions=None):
        if not namespace:
            namespace = metric_name
        if dimensions is None:
            dimensions = {}
        self._queue.put((metric_name, metric_value, namespace, dimensions), block=False)

    def log_record_to_envelope(self, record):
        if isinstance(record, tuple):
            envelope = Envelope(
                iKey=self.options.instrumentation_key,
                tags=dict(utils.azure_monitor_context),
                time=utils.to_iso_str(),
            )
            envelope.name = 'Microsoft.ApplicationInsights.Metric'
            name = record[0]
            value = record[1]
            ns = record[2]
            dimensions = record[3]
            data = MetricData(
                metrics=[
                    {'kind': None,
                     'name': name,
                     'ns': ns,
                     'max': value,
                     'count': 1,
                     'value': value,
                     'min': value,
                     'stdDev': 0}],
                properties=dimensions
            )
            print(data)
            print("properties :" + str(data.properties))
            envelope.data = Data(baseData=data, baseType='MetricData')
            return envelope

        return super().log_record_to_envelope(record)


metric_exporter = AzureMetricPublisher(connection_string="KEY")

metric_exporter.track_metric(metric_name='test_metric',
                             metric_value=42,
                             namespace="test_domain",
                             dimensions={"test_dimension": "value_dimension"})
```

If you run this code @lzchen do you see the dimension in azure monitor ?

Thank you

**Comment by raphaelauv** [comment]
If I remove the custom namespace it work (set null) , the custom dimension appear in the UI of azure monitor and I can click on APPLY SPLITTING and ADD FILTER

But with a custom namespace of a custom metric , the custom dimension are not available to APPLY SPLITTING and ADD FILTER

**Comment by lzchen** [comment]
@raphaelauv 
If you are able to see custom_dimensions appear in app insights then the SDK is working as expected. It is out of scope of Opencensus to know how the UI handles the namespace field and how to apply splitting/filtering properly. Please open up a ticket with your issue to [support](https://azure.microsoft.com/en-us/support/create-ticket/).

**Comment by raphaelauv** [comment]
@Izchen alright ! thank you.

I will open a ticket when I can from my admins ... ( You don't have permission to create a support request ... )
