### ISSUE TITLE
Bump google-cloud-trace to >1.0 in contrib/opencensus-ext-stackdriver

### ISSUE THREAD

**Issue by eddie-scio** [census-instrumentation/opencensus-python#966]
That library is GA now (https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-stackdriver/setup.py#L43

**Comment by aabmass** [comment]
google-cloud-trace >1.0 is python3.6+ only. We still support python2.7 and 3.4, 3.5, so this can't be upgraded

**Comment by eddie-scio** [comment]
Thanks for the explanation.  Is there any timeline or something I can track for Python3.6+ support?

**Comment by aabmass** [comment]
@eddie-scio `opencensus-ext-stackdriver` should work fine for Python3.6+, is there an issue you're running into with the current `google-cloud-trace` version?

**Comment by eddie-scio** [comment]
Oops, I misread your comment.  I am running into some problems, discussing [here](https://github.com/googleapis/python-trace/issues/56) and I was hoping that a version bump would help me out (thought there was something in the underlying gapic libraries around retry logic during span writing).

**Comment by aabmass** [comment]
Hmm ya unfortunately we can't upgrade, but even in the old version of the trace library, there is an option to change the retry configuration: https://github.com/googleapis/python-trace/blob/a4fa87054a34c1dc4e9a69f3a96762ece9cec306/google/cloud/trace_v2/gapic/trace_service_client.py#L399

If the trace folks on the linked issue determine that changing retries is the fix and it solves the issue for you locally, we can probably expose an option for that. I'm not too sure what the story on App Engine Flex is.
