### ISSUE TITLE
Failing to integrate requests module for dependency tracking

### ISSUE THREAD

**Issue by sydneyvert** [census-instrumentation/opencensus-python#968]
**Describe your environment.** 
Versions:
Python - 3.7.4
opencensus - 0.7.11
opencensus-ext-azure - 1.0.5
requests - 2.22.0

**What is the expected behavior?**
Expected requests module to be integrated. Followed the example from the microsoft docs: https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python-dependency#dependencies-with-requests-integration . Code below:
```
from opencensus.trace import config_integration
from opencensus.trace.samplers import ProbabilitySampler
from opencensus.trace.tracer import Tracer
from opencensus.ext.azure.trace_exporter import AzureExporter
import requests

config_integration.trace_integrations(['requests'])

def callback_addRoleName(envelope):
    envelope.tags['ai.cloud.role'] = <role_name>
    return True

azure_exporter = AzureExporter(
    endpoint=<endpoint>,
    instrumentation_key=<instrumentation_key>,
    proxies=<azure_proxy>
 )

azure_exporter.add_telemetry_processor(callback_addRoleName)

tracer = Tracer(
        exporter=azure_exporter,
        sampler=ProbabilitySampler(1.0),
    )

with tracer.span(name="Python Test - Wiki API Call") as span:
    response = requests.get(url='https://www.wikipedia.org/wiki/Rabbit')

```

**What is the actual behavior?**
I get the error message:
```
Failed to integrate module: opencensus.ext.requests.trace
No module named 'opencensus.ext.requests'
```

**Comment by lzchen** [comment]
If you take a look at the first line in the documentation: `Download and install opencensus-ext-requests`. You are getting that error because you don't have that package installed.

**Comment by sydneyvert** [comment]
Thanks for your help
