### ISSUE TITLE
AzureLogHandler doens't work with dbutils.notebook.run in Databricks

### ISSUE THREAD

**Issue by TSienki** [census-instrumentation/opencensus-python#972]
**Describe your environment.** 
It is databricks environment (Runtime Verision: 7.3 LTS). 

**Steps to reproduce.**
1. Notebook run an another notebook, which gets logger from class 
```
class DataBricksLogger:
    _logger = {}

    @classmethod
    def get_logger(
        cls, 
        connection_string: str,
        ) -> logging.Logger:
        if not connection_string in cls._logger.keys():
            logger = logging.getLogger("my_logger")
            
            handler = AzureLogHandler(connection_string=f'InstrumentationKey={connection_string}')
            logger.addHandler(handler)
            cls._logger[connection_string] = logger
        return cls._logger[connection_string]
```  
But this class is not crutial, it doesn't work even if logger is "initialize" as: 
```
logger = logging.getLogger("my_logger")
logger.addHandler( AzureLogHandler(connection_string=f'InstrumentationKey={connection_string}'))
logger.setLevel(logging.INFO)
logger.info(f"New logger started")
```
2. Each step of processing is logged using this logger. 

**What is the expected behavior?**
Logs are sent to Azure Application Insights. 

**What is the actual behavior?**
If I run notebook manually from databricks it works perfectly. But if notebook is run explicitly from another notebook (by dbutils.notebook.run) it doesn't send any log to Azure.

**Additional context.**
 If I add another handler (like StreamHandler to stdout), this second handler works without problem.

**Comment by lzchen** [comment]
What's the exact code used to setup the AzureLogHandler and the code to run the other notebook? Where does `DataBricksLogger`exist and who is calling it?

**Comment by TSienki** [comment]
That is the main notebook 
![image](https://user-images.githubusercontent.com/30471358/97959574-ee559300-1daf-11eb-97de-2ace5a6ed6b9.png)

That is a subordinate notebook, which is run by the main notebook (these ouputs are from run it by hand, so there is Excepetion in second cell for that reason)
![image](https://user-images.githubusercontent.com/30471358/97959629-12b16f80-1db0-11eb-9a5d-a4b122691d00.png)

Here is the subordiate notebook results (run from the main).
![image](https://user-images.githubusercontent.com/30471358/97960071-f82bc600-1db0-11eb-9acd-aace0341b17a.png)

And here logs in Application Insights (there should be 7 records - 3 inits, 2 "Hello world! From module: First, value is 4" with two severity levels , 2 "Hello world! From module: Second, value is 5" also with two severity levels
![image](https://user-images.githubusercontent.com/30471358/97960158-2c06eb80-1db1-11eb-8d5e-bd65f6c12b63.png)


DataBricksLogger is not a problem in this case. It doesn't work properly also without this class, as you can se above.

**Comment by lzchen** [comment]
@TSienki 
Thanks for the screenshots. Just to clarify, should there only be 2 inits? Looks like the sublogger is only called twice right?

Also it seems like `Init new logger` is sent one time? If this is telemetry that resulted from this run, at least we know that some data is being sent to App Insights. if that's the case, the issue must have something to do with running `dbutils.notebook.run` and how it interacts with the Python logger.

Can you try only calling `dbutils.notebook.run` once (with name "First")? Also, can you try placing ALL of your logic (include all of the logging) into one command box?

**Comment by romosandarius** [comment]
@lzchen 
Thank you so much for looking into this! 
I think we have a similar issue, so I will add some details about what we are experiencing. If it turns out that it is not related, please let me know so I will create a separate issue. 
We are running into a similar issue where manually executing the piece of code below via the workspaces UI works perfectly, but scheduling the notebook as a Job breaks the logger so nothing gets published to App Insights. 
```python
import logging
import datetime
from opencensus.ext.azure.log_exporter import AzureLogHandler


logger = logging.getLogger("test app insights")
logger.addHandler(AzureLogHandler(connection_string="InstrumentationKey=<secrets go here>"))

logger.setLevel(logging.INFO)
logger.info("test " + datetime.datetime.now().strftime("%m/%d/%Y, %H:%M:%S"))
```
We've noticed the same issue if we run pure python code by having a Job execute a python script. 

Please let me know if there is something I could try out or if I can provide more information.

**Comment by lzchen** [comment]
@romosandarius 
> scheduling the notebook as a Job

How are you doing this?

> by having a Job execute a python script.

Also this?

**Comment by romosandarius** [comment]
@lzchen 
By using the UI to create a new Databricks Job. 
The job looks like below, where I highlighted in red the tab in Databricks we use to create the job, then underlined in green you can see how we are pointing at the notebook. 
For python scripts instead of having a reference to a notebook, the green area would have a python script stored in Databricks file system. 
![image](https://user-images.githubusercontent.com/9935524/99990762-84c81380-2db4-11eb-8ca4-64dafc71e338.png)

**Comment by romosandarius** [comment]
Hi, @lzchen 

Do you have any idea why we could be having these issues with the jobs? Or if it is at all related to the initial post regarding dbutils? 

/Darius

**Comment by TSienki** [comment]
> @lzchen
> Thank you so much for looking into this!
> I think we have a similar issue, so I will add some details about what we are experiencing. If it turns out that it is not related, please let me know so I will create a separate issue.
> We are running into a similar issue where manually executing the piece of code below via the workspaces UI works perfectly, but scheduling the notebook as a Job breaks the logger so nothing gets published to App Insights.

Finally, I realised what was my problem. And it was caused by small export_interval (15 seconds is default). Notebook exits before logs are sent. For me adding some sleep time after last logging and increasing export_interval were enough.

**Comment by lzchen** [comment]
Closing issue.
