### ISSUE TITLE
Azure logging traces 5 times rather than just the once?

### ISSUE THREAD

**Issue by S-Tasker** [census-instrumentation/opencensus-python#973]
Running:
opencensus==0.7.11
opencensus-ext-azure==1.0.5
opencensus-ext-logging==0.1.0

On Azure Databricks (7.4 (includes Apache Spark 3.0.1, Scala 2.12)) with Python 3. (Unsure exact version)

**Steps to reproduce.**
```
import logging

from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.trace import config_integration
from opencensus.trace.samplers import ProbabilitySampler
from opencensus.trace.tracer import Tracer

config_integration.trace_integrations(['logging'])

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

tracer = Tracer()

def SetupLoggingClient(InstrumentationKey):
  handler = AzureLogHandler(connection_string=f'InstrumentationKey={InstrumentationKey}') 
  logger.addHandler(handler)

  tracer = Tracer(
      exporter=AzureExporter(connection_string=f'InstrumentationKey={InstrumentationKey}'),
      sampler=ProbabilitySampler(1.0) #Never sample - always log.
  )


SetupLoggingClient("KEY")
logger.info("Testing notebook import!")
logger.warning('Chicken')
with tracer.span(name='test'):
    logger.warning('Egg')
logger.warning('Chicken2')
```

**What is the expected behavior?**
Exactly 4 log entries in Azure App Insights:
1 Trace with Info Level, stating "Testing notebook import!"
1 Trace with Warning Level stating "Chicken"
1 Trace with Warning Level stating "Egg"
1 Trace with Warning Level stating "Chicken2"

**What is the actual behavior?**
5 Traces with Info Level, stating "Testing notebook import!"
5 Traces with Warning Level stating "Chicken"
5 Traces with Warning Level stating "Egg"
5 Traces with Warning Level stating "Chicken2"

**Additional context.**
Doesn't matter how i set it up - i.e. in a function, in a separate notebook and import it, or just inline, this occurs, but not always 5 times, sometimes 3 for example.

**Comment by lzchen** [comment]
Perhaps you have the same issue as [this](https://github.com/census-instrumentation/opencensus-python/issues/870)?

**Comment by S-Tasker** [comment]
Oh... Now that makes a lot of sense.
After testing, i can confirm that appears to be the reason indeed.

Thanks for that! I understand databricks isn't a particularly supported use case.
