### ISSUE TITLE
Loosen ikey validation to follow GUID fix reverts to old util

### ISSUE THREAD

**Issue by seamusa** [census-instrumentation/opencensus-python#992]
**Describe your environment.**
I ran a fresh python docker container and installed the opencensus-ext-azure module. Below are the versions of opencensus:

- opencensus               0.7.11
- opencensus-context       0.1.2
- opencensus-ext-azure     1.0.5

**Steps to reproduce.**
Try to run opencensus_ext_azure with the following instrumentation key: 00000000-0000-0000-0000-000000000000

1.  run a python container
```
docker run -it python bash
```
2. install the exporters
```
pip install opencensus-ext-azure
```
3 run python and execute the following
```
import logging
from opencensus.ext.azure.log_exporter import AzureLogHandler

logger = logging.getLogger(__name__)

# TODO: replace the all-zero GUID with your instrumentation key.
logger.addHandler(AzureLogHandler(
    connection_string='InstrumentationKey=00000000-0000-0000-0000-000000000000')
)
```

**What is the expected behavior?**
When running _pip install opencensus-ext-azure_ the bug fix should have been downloaded. I expected the following PR fix to have resolved the bug: https://github.com/census-instrumentation/opencensus-python/pull/986

**What is the actual behavior?**
Running _pip install opencensus-ext-azure_ does not download the bug fix and the older utility file with the bug is downloaded.

**Comment by lzchen** [comment]
Feature has not been released yet, will be out by end of this week.

**Comment by lzchen** [comment]
Should be ready from https://github.com/census-instrumentation/opencensus-python/releases/tag/v0.7.12
