### ISSUE TITLE
0.7.12 Django integration duplicates DB entries

### ISSUE THREAD

**Issue by shabble** [census-instrumentation/opencensus-python#997]
In `opencensus-ext-django==0.7.12`, the following setup line has somehow gotten doubled up, producing duplicate output in traces.

https://github.com/census-instrumentation/opencensus-python/blob/ea40da82b73e6effc646e95c88292f05c1b02096/contrib/opencensus-ext-django/opencensus/ext/django/middleware.py#L167

Looks like it might be a result of the merge in #995 of #775, when the merge destination already had that code present.

**Comment by lzchen** [comment]
Should be fixed with https://pypi.org/project/opencensus-ext-django/0.7.4/
